### ISSUE TITLE
Module qualified file names are not working (not sure who's fault yet!)

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#10]
Noting a problem, but not sure how to address it yet.

The `magento dev:theme-source:deploy` command is used to create a directory tree of symlinks back to the original source code files. Everything works well for Less files in themes.

However, you can also have less files in modules (this never occurs in Magento out of the box). This is so a module can have its own additional styles added via a CSS file. This is for 3rd party extensions in particular.

Currently when you run the above command, it uses an argument of the form "Magento_Customer::foo" to say "foo.less" in the directory of the module Magento_Customer. If you use Magento_Customer/foo the above command currently does not identify the file back with a module (instead it aborts with an error).

The problem with the "::" syntax is "gulp styles" does not compile the 'foo.less' file, because it does understand the concept of "::".

I am not sure if the correct solution is to make the Magento command work out "Magento_Customer" in "Magento_Customer/foo" is a module name, or make the Gulp script understand "::" is special. Without one of these two changes you cannot use this tool with CSS files in modules.

**Comment by Igloczek** [comment]
I'm going to use more clever files list building tool (like in `watch` task), so `files` config will be used only for `deploy` task.

**Comment by alankent** [comment]
Another thing I hit in case relevant - I found a Less variable used in an @import line somewhere

    @import '@{baseUrl}sources/lib/_lib.less';

Just noting it. Would your "clever" code break in that case? If so I might try to recommend against people doing things that way in some documentation being done.

**Comment by Igloczek** [comment]
Yup, it's weird, especially when you dig into this and found that `@baseUrl` is hardcoded in Magento UI as `../` :bomb: 

IMO watcher ignore broken path - not a big deal.

**Comment by Igloczek** [comment]
Main issue resolved in 0.5.0.
Keep open for further feedback about `@baseUrl`

**Comment by alankent** [comment]
There is a "security feature" (aka "bug") to disallow "../" in URLs - it *is* good for external URLs but undesirable for internal URLs (like for "@import" clauses used by Less). Because of support for "client side Less preprocessing", a client web browser needs to be able to resolve the URLs, so there is a bit of murkiness here. I am still trying to understand, but I think it was a misdirected effort - that is, the check was put in the wrong place in the code. As a workaround (!), people discovered you could put a variable into the path - that way real URLs are still checked, but internal ones in Less files get through. It feels like a workaround rather than someone fixing the real issue. The variable is expanded *after* relative paths are resolved (feels strange/broken), I assume by Less. So there may be multiple pieces of strange behavior - to be honest, I don't understand the full flow here yet. If I get that check moved, I suspect we can eliminate the @{baseDir} variable references and just put ".." back into the paths directly.

Before getting the core team to make any changes, I was trying to understand the implication on your tool as well. I don't understand how you can work out the dependencies without knowning the list of CSS files the web page accesses. That is what "files" tells you. It is not all Less files - it is a subset of them, where the subset is not in the code base. So I don't see how you can work it out yourself.

As such, I think I need to get the deploy tool to accept Magento_Customer/foo (instead of Magento_Customer::foo) to avoid you having to know where that file came from. You just want to give the path the HTML page is referencing.  So I think I have convinced myself I need to get that fixed as well regardless.

**Comment by Igloczek** [comment]
Another argument that client side styles processing should be removed (aka. banned) :wink: 

`files` config is no more used outside `deploy` task, it's just list of parameters to CLI.

How I can figure out what files to process? I take every non partial (without `_`) LESS file and compile them - if someone put them in wrong place etc. - their problem. I just want to keep it simple.

BTW. This @import guy (https://github.com/import) might have tough times :smiling_imp:
