### ISSUE TITLE
Backslash - Slash Problem under Windows

### ISSUE THREAD

**Issue by zsoerenm** [SnowdogApps/magento2-frontools#135]
I had a problem using gulp style --theme blank

It couldn't create some symlinks and the error was that in windows the backslash is used for folder structures.

I had to modify inheritance-resolver.js so that
```
themeSrc  = (config.projectPath + theme.src).replace(/\\/g,'/'),
```
This replaces the backslash to normal slash. There is probably a better way to do it.

The same goes for `parentSrc`

**Comment by Igloczek** [comment]
Sorry, but I'm not going to support non-unix systems. Magento doesn't support Windows too -> http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html

Use virtual containers (Docker, Vagrant) or just "pure" virtualization to setup some Linux distro, if you want to stay on Windows.

**Comment by Aerue** [comment]
#BashOnWindows ?

**Comment by Igloczek** [comment]
But why are you trying to reinvent a wheel? Web servers on Windows suck and it's a fact.
Working on unix just solves all issues and you can focus on code, rather than the environment.

**Comment by Aerue** [comment]
I agree that Web Server on Windows just suck, but not with bash...

https://msdn.microsoft.com/fr-fr/commandline/wsl/about

With that i can have my adobe suite running with a true Web server on a unix system.
