### ISSUE TITLE
Styles not rendering correctly with localeOverwrite

### ISSUE THREAD

**Issue by ArjenMiedema** [SnowdogApps/magento2-frontools#145]
When creating a custom theme, which uses Snowdog/blank as it's parent, the `Snowdog/blank/en_US/` folder doesn't have a css subfolder. This results in showing a page with no styling and the following error when opening the `styles.css` file:

**Rendered styles.css**
```Unable to resolve the source file for 'frontend/Snowdog/blank/en_US/css/styles.css'
#0 /Users/arjenmiedema/Sites/magento213/vendor/magento/framework/App/StaticResource.php(97): Magento\Framework\View\Asset\File->getSourceFile()
#1 /Users/arjenmiedema/Sites/magento213/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch()
#2 /Users/arjenmiedema/Sites/magento213/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#3 {main}
```

My themes.json looks like this:

**themes.json**
```{
  "blank": {
    "src"    : "vendor/snowdog/theme-blank-sass",
    "dest"   : "pub/static/frontend/Snowdog/blank",
    "locale" : ["en_US"],
    "lang"   : "scss",
    "postcss": ["plugins.autoprefixer()"]
  },
  "mytheme": {
    "src"             : "app/design/Mytheme/default",
    "dest"            : "pub/static/frontend/Mytheme/default",
    "parent"          : "blank",
    "locale"          : ["nl_NL"],
    "localeOverwrites": true,
    "lang"            : "scss",
    "postcss"         : ["plugins.autoprefixer()"]
  }
}
```

**Comment by Igloczek** [comment]
That's kinda strange, I can't reproduce this issue, but for sure it's not related to Magento itself, b/c Frontools are not connected with M in any way.

Few questions that might help me to fix this issue:
What's your Frontools version?
What's your Node.js version?
Do you have `/styles` directory(ries) in your child theme?
What kind of output do you get during `gulp styles` task?
Did you check if this files are compiled, but saved in different place?

**Comment by ArjenMiedema** [comment]
@Igloczek I checked the issue again on a new installation of Magento 2 (and my MacBook), added my own theme again and did all the necessary steps to get it to work and it now works as expected.

So I couldn't reproduce the issue myself anymore. So it probably had something to do with my own installation. I'm closing the issue, since it doesn't seems to be an issue at all.
