### ISSUE TITLE
Error: ENOENT: no such file or directory, symlink

### ISSUE THREAD

**Issue by roberthowe** [SnowdogApps/magento2-frontools#152]
I am running into issues running gulp commands to compile styles.

Magento 2 install in on XAMPP Windows

**If i run gulp deploy I get the following error**

 Error: ENOENT: no such file or directory, symlink 'C:\xampp\htdocs\magento2.dev\vendor\snowdog\theme-blank-sass\Magento_Swatches\web\images\loader-2.gif' -> 'C:\xampp\htdocs\magento2.dev\pub\static\frontend\Snowdog\blank\en_GBC:\xampp\htdocs\magento2.dev\vendor\snowdog\theme-blank-sass\Magento_Swatches\images\loader-2.gif'

**If I run gulp styles I am getting the following errors**
 
Error: ENOENT: no such file or directory, symlink 'C:\xampp\htdocs\magento2.dev\vendor\snowdog\theme-blank-sass\Magento_AdvancedCheckout\styles\_module.scss' -> 'C:\xampp\htdocs\magento2.dev\var\view_preprocessed\frontools\frontend\Snowdog\blankC:\xampp\htdocs\magento2.dev\vendor\snowdog\theme-blank-sass\Magento_AdvancedCheckout\styles\_module.scss'

**Comment by Igloczek** [comment]
Frontools dosen't and will not support in future Windows, same as Magento core.

**Comment by KeithBauer** [comment]
I was having the same issue. I found to get around this, it is as simple as replacing all '\' characters with '/' in the paths being used. 

Examples:

_helper/inheritance-resolver.js_

Line 36:
``` 
// Create symlinks to all files in this theme. Will overwritte parent symlinks if exist.
    plugins.globby.sync([
      themeSrc + '/**/*.' + theme.lang,
      '!/**/node_modules/**'
    ]).forEach(srcPath => {
    	var slashesBack = new RegExp("\\\\","g"),
    		themeSrcX = themeSrc.replace(slashesBack,'/'),
    		themeDestX = themeDest.replace(slashesBack,'/'),
    		srcPathX = srcPath.replace(slashesBack,'/');
      createSymlink(
        srcPathX,
        themeDestX + srcPathX.replace(themeSrcX, '')
      );
    });
```

and just below that:

```
// We have to handle every locale independly, b/c of possible overwrites
    theme.locale.forEach(locale => {
      // If theme have parent, create symlinks to all avaliabe files and then overwitte only neccessary
      if (theme.parent) {
        const parentSrc = config.projectPath + config.themes[theme.parent].src;
        plugins.globby.sync([
          parentSrc + '/**/*.' + theme.lang,
          '!/**/i18n/**',
          '!/**/node_modules/**'
        ]).forEach(srcPath => {
        	var slashesBack = new RegExp("\\\\","g"),
    		parentSrcX = parentSrc.replace(slashesBack,'/'),
    		themeDestX = themeDest.replace(slashesBack,'/'),
    		srcPathX = srcPath.replace(slashesBack,'/');
          createSymlink(
            srcPathX,
            themeDestX + '/' + locale + srcPathX.replace(parentSrcX, '').replace('/web', '')
          );
        });
      }
```

If you are using command prompt as an Adminstrator, you should not longer receive this error message.
