### ISSUE TITLE
https support with browsersync

### ISSUE THREAD

**Issue by simonsaysforcepush** [SnowdogApps/magento2-frontools#154]
My Magento2 dev sites use https rather than http for security purposes, however browsersync tries only to work with http. In the browsersync documentation they state that https is supported (https://browsersync.io/docs/options#option-https), but I have no idea how or where I would need to implement this in frontools. Do you know if this is possible? I'm using version 0.11.4 for LESS compatibility.

Thanks

**Comment by Igloczek** [comment]
We are not using browsersync `server` opntion (it's for satatic files only), but `proxy`.

> Enable https for localhost development. Note - this is not needed for proxy option as it will be inferred from your target url.

Looks like simple replace of `"proxy": "magento2.dev"` to `"proxy": "https://magento2.dev/"` forces BS to use HTTPS.

```
[03:47:08] Using gulpfile ~/Sites/magento2/vendor/snowdog/frontools/gulpfile.js
[03:47:08] Starting 'browser-sync'...
[03:47:08] Finished 'browser-sync' after 357 ms
[BS] Proxying: https://magento2.dev
[BS] Access URLs:
 --------------------------------------
       Local: https://localhost:3000
    External: https://192.168.0.10:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.10:3001
 --------------------------------------
```

**Comment by simonsaysforcepush** [comment]
Last time I tried that it didn't work, so thank you for getting that fixed! Cheers.

**Comment by Igloczek** [comment]
Happy to help, but I didn't fix anything, just change configuration 😉
