### ISSUE TITLE
BrowserSync injects styles-l.css but nothing changes

### ISSUE THREAD

**Issue by TKlement** [SnowdogApps/magento2-frontools#16]
Hi,

I'm not sure if this is a bug or just my configuration.
But no matter I try there is no effect in the browser.
I change e.g. a background-color then save my file and I can see in the console, that gulp detects changes:

```
[14:47:46] Theme: banana Locale: de_DE banana_product_list.css Compiled!
[BS] 1 file changed (banana_product_list.css)
[14:47:54] Theme: banana Locale: de_DE styles-m.css Compiled!
[BS] 1 file changed (styles-m.css)
[14:47:54] Theme: banana Locale: de_DE styles-l.css Compiled!
[BS] 1 file changed (styles-l.css)
```

After that I see a little tooltip in my browser "inject styles-l.css". I can also register a little flashing in the browser. But then ... nothing happens.
I desperately tried it with !important but again no new background-color.

I also got this error with the standard installation:

> gulp-notify: [Error running Gulp] Error: variable @media-common is undefined in file ...

So I had to declare all variables inside each file but I guess that is not the best way.

Maybe it is important but I extend the porto theme with my banana theme.

The themes.json looks like this:
```
"banana": {
    "src": "../vendor/fruit/magento2-banana-theme-banana",
    "dest": "../pub/static/frontend/Fruit/banana",
    "locale": ["de_DE"],
    "lang": "less",
    "default": true,
    "area": "frontend",
    "vendor": "Fruit",
    "name": "banana",
    "files": [
      "css/styles-m",
      "css/styles-l"
    ]
```

**Comment by Igloczek** [comment]
Do you have enabled CSS merging? BrowserSync can replace live only files with same name.

AFAIK `@media-common` variable comes from Magento UI... are you sure that after `deploy` task, imports list inside `pub/[your_theme]/styles-*.less` looks good?

**Comment by TKlement** [comment]
Only javascript merging is enabled.
That's the annoying thing that the pop-up displays injecting styles-m.css but not the console and nothing  else happens.

@media-common
In my pub-folder is a _styles.less that imports the source folder with all .less files. There are 36 less files inside the source folder.
In which folder is gulp working? In pub or vendor?
I thought it is using the vendor folder. Or can't gulp work before the deploy task?

**Comment by Igloczek** [comment]
On LESS based themes gulp tasks works inside `pub` folder, b/c `deploy` tasks resolves import of theme dependencies (like parent theme imports paths and modules imports paths). If you chose to use LESS theme with `default` parameter set to `true`, you have to use `deploy` tasks before.

Which task did you run to turn on BrowserSync and styles compilation? `gulp dev` or you run separately `browser-sync` and `watch` or `styles`?

When you just refresh page your changes are visible?

**Comment by TKlement** [comment]
I have used "dev gulp" because there is everything in it.
Yes when I refresh the page my changes are visible.
I guess it is because I turned the client side compilation on in the backend.

**Comment by Igloczek** [comment]
Client side compilation is slow, unpredictable and limits styles processing to one step (how about linting or post processing?). Why even think about it?

**Comment by TKlement** [comment]
Ok, I thought I change back to "Server side less compilation" in the backend.
But now I have no more styles in the backend.
I have only styles in the backend with "Client side less compilation".
So that was the reason I had to choose it.

But now again with Magento 2.0.4 I typed
`bin/magento setup:static-content:deploy`
And the compilation ends in my theme with

> variable @media-common is undefined in file ...

I have plenty problems with that LESS.
And it would be a bless to get I worked with GULP and/or your tool.

**Comment by Igloczek** [comment]
Looks like problems with your style files, not (any) tools itself. Could you provide some demo?

**Comment by Igloczek** [comment]
Set developer mode via `bin/magento deploy:mode:set developer` and then try to figure out why your backend compilation fails (IMO looks like problems with importing Magento UI - did you remove some folders?).
I'm going to close this issue, b/c it's not related to frontools itself.

**Comment by TKlement** [comment]
Ok the compilation failure is fixed ... it seems that git and composer had some problems. So after checkout last commits and return everything is fine.

**Comment by TKlement** [comment]
The backend now works with server side less compilation.

**Comment by TKlement** [comment]
Can you at least tell me, if "Server side less compilation" is the correct way to work with your tool?

**Comment by Igloczek** [comment]
Exactly, frontools override output of `setup:static-content` inside `pub` folder.
