### ISSUE TITLE
gulp only watching styles.scss

### ISSUE THREAD

**Issue by andrewkett** [SnowdogApps/magento2-frontools#161]
I have set up a new blank theme. I have gulp running, watching for changes and updating browsersync. My only problem is that watch is only triggering compilation when I make changes to my main styles.scss file. If I create and include new scss files watch will not trigger when I change them. Is there any additional config that I need to do to watch all scss files?

**Comment by Igloczek** [comment]
Did you restart watch task after adding new files? It's unfortunatly necessary.
Btw. Which version do you use?

**Comment by andrewkett** [comment]
I am using 1.2.2, installed with composer. Yea I have restarted everything. Actually it does seem like watch is picking up on changes to other files as sass lint is giving me notices if I have invalid syntax. Its just the sass compilation isn't triggered from other files, only styles.scss

**Comment by andrewkett** [comment]
Ok it seems like watch is ignoring files beginning with an underscore. Is that the expected behaviour? Maybe my understanding is wrong but I would of thought that all css files within the theme directory should trigger sass compilation, even if they are partials? I managed to get this working by modifying a few things in the gulp configuration but without a real solid understanding of all the gulp code I feel like its probably more a hack at the moment than a fix worthy of a pull request.

**Comment by Igloczek** [comment]
Could you add above [this line](https://github.com/SnowdogApps/magento2-frontools/blob/master/task/watch.js#L33) `console.log(dependencyTreeBuilder(theme, file, plugins));` and check output of `watch` task? There should be a long array with all partials to watch.

Will be nice to see your `themes.json` and `styles.scss` of your theme.

**Comment by Igloczek** [comment]
Also will be nice to check if watching partials works on "sass-blank" theme, b/c I'm pretty sure that this feature works well and there is some failure on configuration / customization level.

**Comment by andrewkett** [comment]
Sorry, I have been off the project for the last couple of days. Next time I work on it, probably next week, I'll get this info for you. I will try using the sass-blank theme too.

**Comment by andrewkett** [comment]
Ok figured out what the problem was with the help of console.log(dependencyTreeBuilder(theme, file, plugins));. I was importing my partials with the underscore in front of the file, .eg: `@import '_mypartial'` watch was then looking for `__mypartial`. I am now importing everything with just the name e.g `@import 'mypartial'` it seems to be working better now.
