### ISSUE TITLE
Can't log in when using BrowserSync proxy

### ISSUE THREAD

**Issue by tommypyatt** [SnowdogApps/magento2-frontools#173]
I am able to log in on the frontend using my local dev URL. However, when using the BrowserSync proxy, I am unable to log in or add things to basket.

Environment: Vagrant, Magento EE-2.1.4, Mac OS

I have attempted to find the cause, and noticed that the `form_key` cookie does not exist in the response from Magento via the proxy, and I assume that could be at least related.

Response headers unproxied:

```
...
X-Powered-By: PHP/7.0.2
Set-Cookie: form_key=MdGxJX3GQpGA5rMo; expires=Wed, 08-Mar-2017 11:41:55 GMT; Max-Age=3600; path=/; domain=magento-local.dev
Set-Cookie: mage-messages=%5B%5D; expires=Thu, 08-Mar-2018 10:41:57 GMT; Max-Age=31536000; path=/
Pragma: no-cache
...
```

Response headers via BrowserSync proxy:
```
...
x-powered-by: PHP/7.0.2
set-cookie: mage-messages=%5B%5D; expires=Thu, 08-Mar-2018 10:40:51 GMT; Max-Age=31536000; path=/
pragma: no-cache
...
```

This is possibly a BrowserSync issue but it would be nice to know if this affects others using Magento, or if it is related to my setup.

**Comment by Igloczek** [comment]
I don't have currently idea how to solve it.

Topic on forum - https://community.magento.com/t5/Less-to-Sass-Community-Project/Session-Cookie-issue-on-browser-sync/m-p/58425#U58425

**Comment by tommypyatt** [comment]
@Igloczek no problems, thanks for your input.

It seems that, as that post suggests, the cookie value pass-through was added to BrowserSync many releases ago. Indeed, most of the cookies are passed through correctly. It's the `form_key` cookie specifically that seems absent.

**Comment by adyry** [comment]
Hi there, 
you could try my solution, it solved `Failed to load resource: net::ERR_CONNECTION_REFUSED` problem, and enabled logging, adding to cart:

in browser-sync.json:
`{
  "socket": {
    "domain": "localhost:3000"
  }
}`

inside `yourtheme/Magento_Theme/templates/html/browsersync.phtml`, paste:
`<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://localhost:3000/browser-sync/browser-sync-client.js?v=2.18.8'><\/script>");
    //]]>
</script>`

and extend `default_head_blocks.xml` with custom block pointing to the script above:
`<referenceContainer name="before.body.end">
<block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/browsersync.phtml" name="browserSync" />
 </referenceContainer>`

after running gulp dev, and entering to your local dev, browserSync should connect to the site, which should work with all functionalities.

Best regards, Adrian.

**Comment by Igloczek** [comment]
@iancassidyweb send me this code as a fix a while ago. I didn't tried it yet, but it makes sense for me too.

```js
const bs = require('browser-sync').create();
bs.init({
    proxy: {
        target: 'https://www.example.com/'
    },
    rewriteRules: [
        {
            match: '"domain": ".example.com",',
            replace: ''
        },
    ]
});
```

**Comment by stianmartinsen** [comment]
Another possible solution is to make BrowserSync's proxy run on the same domain as the shop (if you're running gulp from the same host as the site is on).

in browser-sync.json:

```json
{
  "open": "external",
  "proxy": "magento.dev:81",
  "host": "magento.dev"
}
```

Now that it's using a proper domain, I have no problems logging in or adding items to the cart! 🎉

**Comment by tommypyatt** [comment]
@adyry: This works for me but a problem with this approach is that it no longer utilises BrowserSync's proxy capability, which I am relying on for testing on physical devices. If I don't use the proxy, I have to edit the hosts file on any device I would like to test on in order to access my local URL.

Also, I can't really add developer modifications in my project codebases as I work in teams and we would need to make sure this doesn't get deployed to live environments. If you have this problem too, you should be able to add that snippet in miscellaneous HTML in the admin panel, rather than adding custom XML and a template to the codebase.

@stianmartinsen: This is also a good solution. I haven't been able to get it to work fully because I do run gulp on my development environment, with Magento and nginx running in a VM. However, running BrowserSync via a proper domain does negate the dynamic routing provided by BrowserSync. That is, I cannot access my local instance via local IP `192.168.0.x:3000` on mobile devices without modifying each device's hosts file.

@Igloczek: This solution looks interesting, but I haven't been able to get it to work. Using this configuration doesn't seem to affect the appearance (or lack thereof) of the `form_key` cookie. I will continue experimenting with that.

**Comment by tommypyatt** [comment]
For anyone else having similar issues, I have managed to find an interim solution for working on pages that require login or some other cookie-dependant thing like having products in my basket, which is to use the **Copy HTML** of my browser tools to copy the content of the body element and paste the content into my proxied localhost browser window.

This can be done for Android/Apple devices via remote debugging in Chrome/Safari. It's a bit of a pain but it allows me to work locally.

**Comment by tommypyatt** [comment]
@rhodimus, you are a spectacular human being. I love you man.
