### ISSUE TITLE
Not compiling files

### ISSUE THREAD

**Issue by crantron** [SnowdogApps/magento2-frontools#18]
Im not sure if its not finding the files or not. Here is my config. 

```
{
  "backend": {
    "src": "../app/design/adminhtml/Magento/backend",
    "dest": "../pub/static/adminhtml/Magento/backend",
    "locale": ["en_US"],
    "lang": "less",
    "default": true,
    "area": "adminhtml",
    "vendor": "Magento",
    "name": "backend",
    "files": [
      "css/styles-old",
      "css/styles"
    ]
  },
  "blank": {
    "src": "../app/design/frontend/Magento/blank",
    "dest": "../pub/static/frontend/Magento/blank",
    "locale": ["en_US", "pl_PL"],
    "lang": "less",
    "default": true,
    "area": "frontend",
    "vendor": "Magento",
    "name": "blank",
    "files": [
      "css/styles-m",
      "css/styles-l",
      "css/email",
      "css/email-inline"
    ]
  },
  "chefstoys": {
    "src": "../app/design/frontend/ChefsToys/default",
    "dest": "../pub/static/frontend/ChefsToys/default",
    "locale": ["en_US"],
    "lang": "less",
    "default": true,
    "area": "frontend",
    "vendor": "ChefsToys",
    "name": "default",
    "files": [
      "css/styles-m",
      "css/styles-l"
    ]
  },
  "luma": {
    "src": "../app/design/frontend/Magento/luma",
    "dest": "../pub/static/frontend/Magento/luma",
    "locale": ["en_US"],
    "lang": "less",
    "default": true,
    "area": "frontend",
    "vendor": "Magento",
    "name": "luma",
    "files": [
      "css/styles-m",
      "css/styles-l"
    ]
  },
  "demo": {
    "src": "../vendor/snowdog/theme-frontend-demo",
    "dest": "../pub/static/frontend/snowdog/demo",
    "locale": ["en_US", "pl_PL", "ru_RU"],
    "lang": "scss",
    "postcss": ["plugins.autoprefixer()"]
  }
}
```

**Comment by Igloczek** [comment]
Could you provide more informations?
- which verdion are you using
- how errors looks like
- which task/s did you try to run

**Comment by crantron** [comment]
- version : chefstoys 
 - errors : no errors
 - tasks : gulp styles --theme chefstoys

**Comment by Igloczek** [comment]
By version I mean version of frontools 😉 

Does output of this task in console looks like:
```
Theme: chefstoys Locale: en_US styles-m.css Compiled!
Theme: chefstoys Locale: en_US styles-l.css Compiled!
```
If false - did you run `gulp deploy` before?
If true - did you have your style files in `pub/static/frontend/ChefsToys/en_US/css `?

**Comment by crantron** [comment]
also my less files form my theme reside in:

```/app/design/frontend/ChefsToys/default/web/css```

**Comment by crantron** [comment]
- gulp deploy output 

```
[10:34:32] Using gulpfile ~/public_html/shop/tools/gulpfile.js
[10:34:32] Starting 'deploy'...
[10:34:50] Finished 'deploy' after 18 s
```

**Comment by crantron** [comment]
- gulp styles --theme chefstoys output 
```
[10:35:38] Using gulpfile ~/public_html/shop/tools/gulpfile.js
[10:35:38] Starting 'styles'...
[10:35:38] Starting 'less:chefstoys:en_US'...
[10:35:38] Finished 'styles' after 651 ms
[10:35:38] Finished 'less:chefstoys:en_US' after 659 ms

```

**Comment by Igloczek** [comment]
If you run `bin/magento setup:static-content:deploy` your styles are compiling?

**Comment by Igloczek** [comment]
Does your `pub/static/frontend/ChefsToys/en_US/` folder contains symlinks to your theme in `app` folder?

It looks like problems with Magento, not frontools itself.

**Comment by crantron** [comment]
Im not using symlinks, I'm using the copy method. Symlinks are throwing permission issues.

**Comment by crantron** [comment]
also , clear out pub/static before running gulp .

**Comment by Igloczek** [comment]
Nevermind, does the less files in `pub` looks good?
Which version of frontools are you using?

**Comment by crantron** [comment]
- when they get processed via development mode by php yeah everything works fine. 
- snowdog/frontools": "^0.6.1"

**Comment by Igloczek** [comment]
1. Read package version from `tools/composer.json`
2. Remove `pub/static/frontend/ChefsToys`
3. `gulp deploy --theme chefstoys`
4. Check if LESS files in `pub/static/frontend/ChefsToys/en_US/css` looks good.

**Comment by crantron** [comment]
this is tools/composer.json

```
{
    "name": "snowdog/frontools",
    "description": "Set of front-end tools for Magento 2, based on Gulp.js",
    "version": "0.6.1",
    "license": "MIT",
    "type": "magento2-component",
    "extra": {
	"map": [
            [
              "*",
              "tools"
            ]
	]
    }
}
```

**Comment by crantron** [comment]
- gulp deploy --theme chefstoys output 
```
[11:03:43] Using gulpfile ~/public_html/shop/tools/gulpfile.js
[11:03:43] Starting 'deploy'...
[11:03:43] [Warining] This tasks is designed only for LESS themes which use @magento-import
[11:03:43] Finished 'deploy' after 3.63 ms
```

**Comment by Igloczek** [comment]
Did you change config? This msg shows only for themes without `"default":" true`...

**Comment by crantron** [comment]
ah I was just messing with the options seeing what would change. Ill change that back

**Comment by crantron** [comment]
we'll s*** , it works .

**Comment by crantron** [comment]
so deploy is what I want to use?

**Comment by Igloczek** [comment]
You need `deploy` task to link files from `app` of `vendor` folder to `pub` and resole `@magento_import` depencecies.

I have to work on better docs for this tools :)

**Comment by crantron** [comment]
last question, is there a way to compile both less and sass? I'm using luma as a parent theme and it's all in less , but my template I created is in sass. recommendations?

**Comment by Igloczek** [comment]
Um... maybe define second theme in confg, but use same paths and sass as lang? It might works...

Or just use our second product - [SASS based blank theme](https://github.com/SnowdogApps/magento2-theme-blank-sass) - but have in mind this in still not a rock stable version 😉

**Comment by crantron** [comment]
cool thank you so much for your help :) "rock solid " :P

**Comment by Shashank-Bhatt1** [comment]
Hi Same issue here,
What was the solution? if i run gulp watch then it is only linting files but not compiling.

**Comment by Igloczek** [comment]
@Shashank-Bhatt1 this is a 5 years old issue, please open new one, with detailed description of your config, what you are doing and what you want to achieve.
