### ISSUE TITLE
Babel files without *.babel.js

### ISSUE THREAD

**Issue by MattLishman** [SnowdogApps/magento2-frontools#180]
I can't find any documentation on how babel should be used.

If I add some ES6 to a `.js` file I don't see it get transpiled with `gulp babel` (or any gulp task).

I took a look through the babel task code and found 

```
return gulp.src(
    file || srcBase + '/**/*.babel.js',
    { base: srcBase }
)
```
in `/helper/babel.js:27`

This makes it seem like adding `.babel` to the end of a file will make the babel task pick it up.
I managed to make it transpile, but i'm not 100% sure what I did. 

Besides the transpiling, everything else works (files are moved and symlinks setup)

However, I have a few issues and was wondering if anyone can help me out.
I feel like I might be misunderstanding:

* Needing to add `.babel.js` isn't standard. Are we required to do this and if so, why?
* Which gulp tasks run the babel task? `deploy` doesn't seem to and `dev` only seems to do it sometimes (normally after a `gulp babel`)
* Running `gulp babel` also transpiled my *original* file, which is definitely wrong. Is this intentional?
* I have no `.babelrc` or any type of babel config file, do I need one?

**Comment by Igloczek** [comment]
1. By default of M2 code is written in ES5, so there is no need to transpile everything. Adding some kind of prefix was the easiest way to process only ES6 files.
2. What you mean by "only sometimes"? I'm not sure if this should be a part `deploy` (tasks names need a refactor, to address real use case)
3. Sorry, but I can't reproduce this issue locally and looking on the code it makes no sense at all. Let's remove `pub/static` and `var/view_preprocessed`, then run again `gulp inheritance` and `gulp babel`.
4. For now `.babelrc` files are not supported. I need to write a parser, b/c using presets in Gulp require additional work. For now, Frontools support only `babel-preset-env` and you can manually adjust setting in `helper/babel.js`

**Comment by MattLishman** [comment]
Thanks for the fast response!

1. I appreciate that transpiling **all** Magento's js is a poor idea, but we intend to write all **our** JavaScript in ES6, adding `.babel.js` to the end ties us to babel (and frontools). Would it be possible to have a configuration that allows all files in configured directories to be run through babel? (I can take a look at doing a PR for this).
Something like
```
{
  "babel": {
    "src": [
      "Theme_name/web/js/*.js",
      "Theme_name/some_module/path/to/js/*.js"
    ]
  }
}
```

2. I might misunderstand how the tasks are intended to be used, but I thought I would run `deploy` when I want to create a static build of the site. If this is the case, I need babel to run so that the js is transpiled. Either way, when should babel be run? During `dev`? Is this thinking incorrect?

3. I will continue to investigate this and see if I still see it. I see the js being symlinked rather than copied, is this right?

**Comment by Igloczek** [comment]
1. Renaming bunch of files to non-babel-prefixed version is a 5 min task and still, you can use i.e. Babel as CLI and transpile these files. IMO it's completely not necessary. I'm just thinking about an option to rename output files to not have `babel`.
2. For now, all files inside any `web` folder are copied to `pub` including this one with `babel`. Basically, I'd say to stick with M based compilation for now (will do exactly same things and as long as you are in developer mode, you don't have to worry about it)
3. `deploy` task by default (without `--prod` flag) symlink files to `pub`, so there might be a source of your issues - run `deploy` first and then `gulp babel` which tries to save in symlink dir and overwrite default file. At all there is no need to use `gulp deploy` on local.

**Comment by MattLishman** [comment]
1. I still don't quite see the justification for needing to append `.babel` to files you want to transpile. Shouldn't all user written JavaScript just be transpiled, that way you can just write ES6 in all your JavaScript? Using config paths and gulp globs you could omit anything that is third party and only transpile user written JavaScript. Passing ES5 JS through babel won't change anything so besides speed (which you can improve with caching etc.) there isn't really any loss.
I'll take a look at the tasks and see what I can do. I've got it to work changing the tasks directly, i'll try add a config.

I'm starting to get the hang of the gulp files, can I just check a few things though?

I was seeing symlinks, rather than copied files because I ran a `gulp deploy` (no `--prod`). This is what caused my issue.
Does this mean if babel is run the file should be copied, rather than symlinked to prevent this issue?

If `deploy` isn't needed on development, does `gulp dev` or `gulp dev --prod` do an initial build or does it only start to build after a file is changed?
(say I remove `pub/static/frontend`, will running `gulp dev --prod` rebuild it all again?)
If not, how do I build my project while developing?
I expected to run `gulp dev`, have the project build (as if doing a deploy) and then watch for subsequent changes. Though this might be the wrong expectation as I might misunderstand.

Shouldn't `deploy` run babel too so the code is build correctly? Otherwise you are left with untranspiled code.

I essentially want to be able to build my whole project (not minified) and then watch for changes. I can't `gulp deploy && gulp dev` because of the symlink issue.

Hope this all makes sense.
Thanks, the help!

**Comment by Igloczek** [comment]
1. Sorry, but I see there more issues than possibly fixed problems and I'm not going to change it.

`gulp dev` as a name suggest is designed for development so running something like `gulp development --production` is a ridiculous idea.

There is no point in using `gulp deploy` during development and just ignore this task, just b/c it's work in progress, as a part of unfinished #25.

How to:
- remove `pub/static` - to remove shit generated by `gulp deploy`
- run `gulp inheritance && gulp babel` - to transpile ES6 (I need to combine this task together)
- run `gulp styles` - to compile styles
- run `gulp dev` - to watch changes and process necessary files

**Comment by MattLishman** [comment]
Okay, I don't feel strongly enough about it to change it. I'll add `.babel` to files I want to transpile.
I couldn't see this in the documentation, is it worth adding?
This answers my question on how to get babel working anyway, thanks!

I agree, adding `--prod` to `dev` is incorrect, I misread the documentation and your previous comment (I misread `deploy` as `dev`). Ignore that part.

>How to:
>
> * remove pub/static - to remove shit generated by gulp deploy
> * run gulp inheritance && gulp babel - to transpile ES6 (I need to combine this task together)
> * run gulp styles - to compile styles
>* run gulp dev - to watch changes and process necessary files on the fly

This is essentially what I was looking for, `gulp inheritance && gulp babel && gulp styles && gulp dev` 👍 

What I was trying to say was: Shouldn't `gulp inheritance && gulp babel && gulp styles` be run at the start of `gulp dev` to ensure everything is up to date before watching? And so that you don't need to run these 4 commands every time `pub/static` is removed?

**Comment by Igloczek** [comment]
An idea to run all necessary compilations steps on `gulp dev` is really nice. Added to develop, will be released with next version.
