### ISSUE TITLE
Using the .min.css files when using --prod flag

### ISSUE THREAD

**Issue by kozie** [SnowdogApps/magento2-frontools#184]
Using the --prod flag now produces minified .min.css files instead of the normal (for example) styles.css.

I know i can just edit this in my layout files but that's not the point. I can add both normal and minified styles to my layout but that seems ugly thus isn't really a solution.

Am i missing some sort of conditional thing i can apply to my layout or something? I mean, i support the use of minified files tho but it seems somewhat unusable right now.

Thanks in advance

**Comment by Igloczek** [comment]
https://community.magento.com/t5/Less-to-Sass-Community-Project/Frontools-production-styles-with-min-suffix/m-p/58823#U58823

**Comment by kozie** [comment]
Well, that explains ^_^ Many thanks! :)

**Comment by mattgreenfield** [comment]
FYI: you can now add `"disableSuffix": "true",` to themes.json, allowing you to run `--prod` without adding `.min` to all CSS files. 

Thanks to this Pull Request https://github.com/SnowdogApps/magento2-frontools/pull/208

**Comment by kozie** [comment]
Thanks for the update @mattgreenfield ! :)
