### ISSUE TITLE
R.JS and merging of JS/webpack

### ISSUE THREAD

**Issue by Khaleel** [SnowdogApps/magento2-frontools#197]
Hi Guys

I am working on some PageSpeed optimisations and I am wanting or planning to use RequireJS optimiser or switch to webpack

Has anyone shifted easily or managed to merge all the JS without all the DNS calls that get fired. It is killing us in pagespeed regardless of async calls. I am worried that even making one JS we would still need to update data-mage init calls in the HTML

Any help would be appreciated

**Comment by Igloczek** [comment]
It's a good topic, but not related to Frontools itself.
We have a Slack channel for front-end talks, let's join and move this discussion.

Here is a short form you have to fill up to join - https://docs.google.com/forms/d/18vJcGCsAe4vdnayS2O8nRErTLUNjqnk53vxoT3SujK0/viewform?edit_requested=true

**Comment by Khaleel** [comment]
I filled the form. Thank you.
