### ISSUE TITLE
Running browsersync from inside Docker container

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#2]
I was trying to run the code from inside a Docker container, but was having some trouble with browsersync. This is not necessarily a request to change the code, just trying to work out if it can be used inside Docker.

Does browsersync mandate you hard code the host name into the configuration files?  What if the host name is not known? (I expand below.)

When I run Docker on Windows I normally use 192.168.99.100 to connect to the container (the IP address of VirtualBox). Inside the container it thinks its address is 172.17.0.2. (Docker does all the network mapping between the two IP addresses.) So external requests come in with a URL of 192.168.99.100, and formed URLs returned by the web server use this same IP address. Otherwise it would not work.

I have Magento 2 installed without specifying --base-url, meaning it will just use the host name of the request. With Docker, I just use the IP address 192.168.99.100 - Magento 2 then injects this as the "hostname" into any responses. It does not need to be told what host name to use. This is convenient as it reduces local configuration to get this going. However...

There is a browsersync 'proxy' setting of 'm2test.dev'. When I type in the URL by hand, it redirects me to m2test.dev (which does not exist on Windows and so fails). I would rather not require the developer to add m2test.dev to their local /etc/hosts file if possible (I am trying to simplify setup by removing steps). But inside the container it is not told about 192.168.99.100. Is there any way around this? Can you get "proxy" mode working without hard coding the hostname to use?  E.g. using 0.0.0.0 or similar? As far as I can see it has to know the host name to work.

Also, can I get the default port people normally connect on to be 80? Kitematic (a GUI on the front of Docker) appears to know 80 is HTTP, so fires up a web browser automatically. Port 3000 and 3001 however do not - they open up explorer, probably because it is not sure what type of protocol it is. So I would like to use port 80 inside the docker container instead of 3000 (assuming developers are supposed to access 3000 to get browsersync functionality?)  Or is 80 still accessible (without browsersync) and 3000 is with browsersync (and 3001 is the browsersync admin UI)

In case useful, I found this Docker container: https://github.com/ustwo/docker-browser-sync - it talks about adding a hostname.

(a few hours later).... Hmmm. Using "-net=host" in Docker might help a little - now the container knows the IP address.  But it would be much better if did not have to specify the host name, and instead it used the hostname from the current URL instead. Can that be done with browser sync do you know?

(even longer later).... http://stackoverflow.com/questions/25410284/gulp-browser-sync-redirect-api-request-via-proxy

Frankly I am just plain confused. I set the proxy to 127.0.0.1 for example, and then hit 192.168.99.100:3000 (the VM). It looks like it redirected me to 192.168.99.100:80 - almost like "I don't think I am meant to proxy that request". Its like its using the setting for both matching in bound requests and where to forward requests too. I want it to proxy everything. I created https://github.com/BrowserSync/browser-sync/issues/984 to see if I get an answer from there.

**Comment by Igloczek** [comment]
BS config is currently hardcoded, sorry, but I missed this little thing.

BS have to use different port than 80, because you web server use it too (will be race condition or smth just die). You can specify custom port in BS config - https://browsersync.io/docs/options/#option-port

Unfortunately I'm not so familiar with Docker, but you should try to map port 80 on local to 3000  inside Docker container via `docker run -p 80:3000 [..]` 
Related docs: https://docs.docker.com/engine/userguide/usingdocker/#viewing-our-web-application-container

**Comment by alankent** [comment]
I found one reported solution: http://stackoverflow.com/questions/28500695/browsersync-doesnt-set-the-right-local-url - but unfortunately it involves modifying the HTML to include the <script> tag by hand rather than having a proxy do it. I am not sure how convenient that will be for developers - the proxy server sounds more convenient.

**Comment by Igloczek** [comment]
Maybe run BS outside and pass container IP as proxy parameter?
That "solution" with HTML injecting sucks...

**Comment by alankent** [comment]
I think I have found recipe that works, and it is as simple as using "http://localhost" in the tasks/browsersync.json file. I tried putting http://localhost:80, but it seems *sometimes* the web server response leaves off the port number, which causes the proxy not to match. E.g. 302 (relocates) appear to do this. It is not wrong, but the proxy does not seem to be smart enough to realize http://localhost:80 and http://localhost is the same. Dropping the port number from the config seems to be going reasonably well.

**Comment by alankent** [comment]
Just for the record, I actually found there was an issue with Magento caching of configuration details. If you don't specify a --base-url= then it caches the first host name that it sees. Normally that is fine, but not in my case. Turning of cache for config solved the issue for now.

**Comment by joshuaadickerson** [comment]
@alankent can you elaborate on your solution? 

I currently have M2 in a container (two actually - one for php and another for Nginx) and then gulp/frontools in another container.
