### ISSUE TITLE
"modules" option requires documentation

### ISSUE THREAD

**Issue by mattgreenfield** [SnowdogApps/magento2-frontools#200]
As per the title, I am a little lost as to what the 'modules' option in `themes.json` is doing.

From what I can tell (having played around with it a bit), it will compile a `.scss` file in the given module directory in to CSS. However it will not inherit any of the themes variables, the magento-ui mixins etc.

I found [the pull request](https://github.com/SnowdogApps/magento2-frontools/pull/166) and so my next thought was maybe that I could import the module partials in to my theme without having to `../../[vendor_name]/[module_name]` - and actually this would be the preferred solution for me.

Any help would be greatly appreciated,
Thanks

**Comment by Igloczek** [comment]
This option will map external resources to your theme. Ofc it let you use external stylesheets, but it's not designed only for this purpose.

Frontools will not make any magical things like "inherit any of the themes variables", it's developers job to write proper imports and do with code what they need, I'm not going to follow bad practices from M2 core, where everyone wonders what `// magento_import` is and how it works.

If you are curious how it works, setup some module, run `gulp inheritance`, then open`var/view_preprocessed/frontools` and you will find there your theme with external module mapped inside them (all tasks works only on symlinks in this directory).
You can also read the code of inheritance resolver there -> https://github.com/SnowdogApps/magento2-frontools/blob/master/helper/inheritance-resolver.js

I'm closing this issue, b/c I know that docs aren't great, but don't have enough time to work on it. 
If you have a suggestion how to improve it, feel free to send a pull request.

**Comment by mattgreenfield** [comment]
Thanks for the help, I've had a play around and think I now understand it.
I'm happy to make a pull request.
