### ISSUE TITLE
Frontools 2.0

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-frontools#201]
Idea:
Make Frontools a plugin system and publish only as Node.js package (npm) to improve extendability and modularity, making it more front-end oriented at same time.

Usage will be simple:
package.json
```json
{
  "dependencies": {
    "magento2-frontools": "^2.0.0",
    "magento2-frontools-babel": "~0.2.0",
    "magento2-frontools-scss": "^1.0.0"
  }
}
```

Tools that might be useful:
- https://github.com/lerna/lerna

**Comment by kjugi** [comment]
Bring webpack here 😁

**Comment by joshuaadickerson** [comment]
If you wanted to also support Composer installs (ugh), you could just check the parent directory name for config.projectPath. If it's composer, go up 3 directories. If it's node_modules, go up 2. You could even have it fallback to search for an app directory and inside that a design directory.

**Comment by Igloczek** [comment]
@joshuaadickerson even if the core of Frontools will be available only as a Node.js package, there will be a Composer package required to deal with other required files like `package.json` and be able to use them in M2 project.
