### ISSUE TITLE
Gulp Watch - Only compiles while watching only the root .scss file?

### ISSUE THREAD

**Issue by mosaiceye** [SnowdogApps/magento2-frontools#211]
Here's my themes.json:
```
{
  "blank": {
    "src": "vendor/snowdog/theme-blank-sass",
    "dest": "pub/static/frontend/Snowdog/blank",
    "locale": ["en_US"],
    "ignore": [".test"]
  },
  "youngstown-gloves": {
    "src": "app/design/frontend/{client}/{theme-name}",
    "dest": "pub/static/frontend/{client}/{theme-name}",
    "locale": ["en_US"],
    "localeOverwrites": true,
    "parent": "blank"
  }
}
```
It pretty basic so far, however I'd like it to trigger any SCSS file changes in the folder not just the root SCSS file. My root is called `styles.scss` and it has this:
```
@import "util/index";
@import "layout/index";
```

Thoughts?
Thanks again, cool library!
Tony

**Comment by Igloczek** [comment]
It should work out of the box. 

Could you show me your theme directory structure and describe how did you try to enable watcher?

BTW. `localeOverwrites` in you case is pointless and you should disable it.

**Comment by Igloczek** [comment]
Lack of feedback.

**Comment by Ig0r-M** [comment]
@Igloczek can you explain what is `localeOverwrites` exactly used for or pinpoint where it has information regarding this.

**Comment by Igloczek** [comment]
`localeOverwrites` and all logic related to this feature was removed in version 1.5.0
