### ISSUE TITLE
Watcher ignore some nested SASS partials

### ISSUE THREAD

**Issue by mattkrupnik** [SnowdogApps/magento2-frontools#215]
Hello,

at first I want to point out that everything works fine but don't know why I can't overwrite `_cart.scss` in `MY-THEME/Magento_Checkout/styles/module/` when working on `gulp dev`. Strange is that I can overwrite `_minicart.scss` in this same directory then styles are compiled and BrowserSync work.

Regards
Matt

**Comment by talalus** [comment]
1. Try to re-run `gulp dev` again after adding new scss file to fix inheritance because currently watch task can't watch new added files.
2. If (1) didn't work try to copy Magento_Checkout/styles/_module.scss to your sub theme.

**Comment by mattkrupnik** [comment]
1. I did `gulp styles` after adding new scss, next `gulp dev`.
2. Added yet `_module.scss` to this directory - but no luck.

**Comment by Igloczek** [comment]
- Which version of Frontools are you using?
- Let's try to manually remove`pub/static/your-theme` and `var/view_preprocessed/frontools` directories and re-run `gulp styles`
- Did you modify `styles/styles.scss` file? Are you sure that your partial is still imported?
- Let's try to make an intentional mistake in this file i.e. add some random string instead valid SCSS code and then run `gulp styles`. It should throw you an error it file is in right place and it's imported (it works for me localy).

**Comment by mattkrupnik** [comment]
Hello @Igloczek 

My Frontools version 1.4.5.

I removed `pub/static/your-theme` and `var/view_preprocessed/frontools` but no luck, styles.scss wasn't modify. Also I did mistake in file and that show the error in right place. 

Also added some code to `_shipping.scss` with `gulp watch` and looks fine `Theme: basic-child File: _shipping.scss - SASS Lint finished.` but file isn't compiled, have this same problem with this file `_shipping.scss` .

**Comment by Igloczek** [comment]
So if you get an error, overwrite works perfectly fine, maybe you just expect different results or use CSS file that's not generated through Frontools?

For the sake of debugging this issue, stop using a `gulp dev` or `gulp watch` and use only `gulp styles`. Watcher has some known bugs, but it's not related to your issues at all.

**Comment by mattkrupnik** [comment]
When I run `gulp dev` or `gulp watch` just want to watch files and take a note of changes on website and as I wrote before on some scss files thats work fine.

For example if I change _minicart.scss I have note as below and see resutls on website
- `File /frontend/<Vendor>/<theme>/Magento_Checkout/styles/module/_cart.scss changed.`
- `Theme: basic-child File: _cart.scss - SASS Lint finished.`
- `Theme: basic-child styles.css Compiled!`

When I do this same for example on `_shipping.scss` then I have just 
- `Theme: basic-child File: _shipping.scss - SASS Lint finished.` and no info about that file was changed also changes aren't saved in `styles.scss` and I can't note any results on website.

I did update, reinstall, `gulp styles`, deploy etc. but no luck - I don't count on solving the problem but maybe some tips.

**Comment by Igloczek** [comment]
I asked you to not use `dev` and `watch` task, b/c it just add more complexity to debugging 🙄 

If you made some change, i.e. replace all code of `_shipping.scss` to i.e. `body { background: red; }` and then run *only* `gulp styles` it works or not?

**Comment by mattkrupnik** [comment]
Yes, if I run only `gulp styles` then that works but as you know in this way I can't watch the files.

**Comment by Igloczek** [comment]
Okay, so it's a known bug, related to the watcher, not a lack of ability to overwrite partials generally. 
I have an idea how to refactor this code and probably will be released in some (probably not close) future as v1.5.0

**Comment by keijsers** [comment]
Hi @Igloczek and @mattkrupnik 

We had the same problem. The 'problem' is in de file: 
vendor\snowdog\frontools\helper\dependency-tree-builder.js (line: 22)
It is adding a '/_' to the file path of all partials found via the regex: "/(?:\n@import )(?:'|")(.*)(?:'|")/g;". So if you @import partials using a path that already includes a '/_' the dependencyTree function adds another '_' to the partials path resulting in a broken path.

Two possible solutions:
1) Use no '_' (underscore) in your @import declarations
2) refactor the dependency-tree-builder.js function to catch partials already having an '_' in their @import path and don't add another underscore to their path.

I'm currently going for option 1 :)

**Comment by Igloczek** [comment]
@keijsers `clean-import-paths` (https://github.com/sasstools/sass-lint/blob/develop/docs/rules/clean-import-paths.md) are defined as `sass-lint` rule (https://github.com/SnowdogApps/magento2-frontools/blob/master/config/sass-lint.yml.sample#L11) and you should use follow it or at least keep it manually.

So it's not a source on the issue, you are just not following code standards in your project 😉

**Comment by keijsers** [comment]
Hi @Igloczek 

Thanks for pointing out this code standard. I did not know about it.

But this still could be the problem for @mattkrupnik. So hopefully he has some use of my comment :)

**Comment by Igloczek** [comment]
v1.5.0 with new `watch` task released
