### ISSUE TITLE
Weird module stylesheets compilation path

### ISSUE THREAD

**Issue by adyry** [SnowdogApps/magento2-frontools#221]
Hello,
Due to our project size we've decided to move our modules scss files outside theme to each respective module.
Problem, which I've encountered is that frontools compile css files to
`/pub/../[Vendor_Module]/view/frontend/web/css`
 instead of simple 
`/pub/../[Vendor_Module]/css `
 
Here is our module structure, and compilation output:
Structure:
`/app/code/PandaGroup/Careers/view/frontend/web/css/styles.scss`
Compiles to:
`/pub/ ... /en_US/PandaGroup_Careers/view/frontend/web/css/styles.css`
And in view_preprocessed:
`/var/view_preprocessed/frontools/frontend/ ... /PandaGroup_Careers/view/frontend/web/css/styles.scss`
 
Module declaration inside themes.json:
```
"modules": {
        "PandaGroup_Careers": "app/code/PandaGroup/Careers"
    }
```
Is it a bug or I'm doing something wrong? I use our fork of frontools 1.3.3.

**Comment by Igloczek** [comment]
Frontools handle only front-end part, so expects paths to front-end code, not whole module, that's why it looks "weird".

Change your modules configuration to
```js
"modules": {
    "PandaGroup_Careers": "/app/code/PandaGroup/Careers/view/frontend"
}
```
and it should work as you expected.

BTW. Remember to set `web/css` as `stylesDir`.

**Comment by adyry** [comment]
Ah, great thanks, it works now!
Except, I've had to use:
`"PandaGroup_Careers": "app/code/PandaGroup/Careers/view/frontend"`
without leading slash, as providing it produced even funnier path inside /pub/ 
(it mimicked my complete localhost file structure, i.e. `/pub/ ... /en_US/home/user/www/...... /styles.css` ;) )

**Comment by Igloczek** [comment]
Yeah, that leading `/` was added accidentally 😉
