### ISSUE TITLE
npm ERR! Invalid name: "@gulp-sourcemaps/map-sources"

### ISSUE THREAD

**Issue by mosaiceye** [SnowdogApps/magento2-frontools#224]
Just pulled the latest 1.5.2, and I'm getting this error when I run "npm install". Thoughts? Thanks,Tony

**Comment by Igloczek** [comment]
What's your node and npm version?
Did you tried to remove `node_modules` and do clean installation?

**Comment by mosaiceye** [comment]
Yeah npm: 3.10.10, node: v6.11.0. And yes, node_modules has been removed.

**Comment by Igloczek** [comment]
It's probably one of those issues and it's not related to frontools at all.

https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/298

**Comment by mosaiceye** [comment]
I added this: "gulp-sourcemaps": "2.4.1", to your "package.json" file and it fixed it for me.
