### ISSUE TITLE
Clean task removes requirejs-config

### ISSUE THREAD

**Issue by quisse** [SnowdogApps/magento2-frontools#226]
When i first run the clean task & after the dev task, the requirejs-config.js file which Magento generates in `pub/static`, gets removed and only returns when i do `bin/magento cache:clean` after `gulp clean` and before `gulp dev`.

**Comment by Igloczek** [comment]
Removing the `pub/static` content is the purpose of clean task.

Read the documentation to understand how M2 deploment modes and caching works.

**Comment by quisse** [comment]
Yes i know that. But i don't get why Magento isn't adding the `pub/static/_requirejs/frontend/Storefront/wegro-theme/en_US/requirejs-config.js` file again after the pub/static directory gets cleared...

**Comment by Igloczek** [comment]
Fisr of all be sure you use `developer` mode, b/c probably you are on `default`.

Clear task doesn't clear the cache and you shouldn't use it, if you don't expect to remove everything from `pub/static` (which is in 99.99% cases just pointless).

If you need to use M2 CLI commands, use M2 CLI commands, not front-end tools (b/c they will never have any connection with PHP code / Magento core).

**Comment by quisse** [comment]
I'm on developer mode. Other files do get symlinked (except css files generated by frontools, offcourse).
Ok, I get your point. I'm checking with the guys of Magento why the file isn't replaced when removed. 
Thx for your time.
