### ISSUE TITLE
Add SASS and CSS linting

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-frontools#23]

**Comment by timneutkens** [comment]
Should this be a port of the linting commands found in blank-sass? Already fixed #24's error throwing for blank-sass as you know. https://github.com/SnowdogApps/magento2-theme-blank-sass/pull/78

**Comment by Igloczek** [comment]
Yup. I think it's good enough.

**Comment by timneutkens** [comment]
I'll create a pull request.
