### ISSUE TITLE
Scss from modules path's config

### ISSUE THREAD

**Issue by cernfortech** [SnowdogApps/magento2-frontools#235]
Hei, I've stucked with your new great option: "Modules" in the themes.json.
Could you please advise me how to solve described below issue? Or maybe there no such functionality and I'm searching for it in vain..

My themes.json looks in such way:
```
"convert-lanullva": {
    "src"            : "app/design/frontend/Convert/lanullva",
    "dest"           : "pub/static/frontend/Convert/lanullva",
    "locale"         : ["nb_NO"],
    "lang"           : "scss",
    "parent"         : "convert-two",
    "disableSuffix"  : true,
    "modules": {
      "Convert_ProductSlideIn": "vendor/convert/module-product-slidein"
    },
    "postcss"        : ["plugins.autoprefixer()"]
  }
```
I've added modules option in themes.json and execute 'gulp inheritance' command.
I see that 'gulp watch' task see my changes in the "vendor/convert/module-product-slidein" folder:

`[14:13:52] Change detected. Theme: convert-lanullva File: var/view_preprocessed/frontools/frontend/Convert/lanullva/Convert_ProductSlideIn/view/frontend/styles/module/_common.scss`

also I've included it in my 'convert-lanullva' theme styles.scss as :
`@import "../Convert_ProductSlideIn/view/frontend/web/styles/module";`

but after that 'convert-lanullva' theme is not compiled automatically after changing _module.scss in 'Convert_ProductSlideIn' folder. I thought that this option were added to resolve styles inheritance during the compilation. No? 

PS. Also due to this pull-request https://github.com/SnowdogApps/magento2-frontools/pull/227 I haven't realized how could I use "Modules" option in themes.config to include Foundation styles from the bower folder.

**Comment by Igloczek** [comment]
```
    "modules": {
      "Convert_ProductSlideIn": "vendor/convert/module-product-slidein/view/frontend"
    },
```
Always define a path to front-end resources, not whole module.
After this small change and adjusting imports everything should work fine.

**Comment by cernfortech** [comment]
Hei! I've changed my path as you adviced:

I have such path to required file (changed it a little bit):
`www/lanullva/vendor/convert/module-product-slidein/view/frontend/styles/_module.scss`

and after executing inheritance task I'm including it in the styles.scss as:
`@import "../Convert_ProductSlideIn/styles/module";`

But unfortunatelly styles.scss of 'convert-lanullva' theme still isn't compiling when I'm changing _module.scss in 'Convert_ProductSlideIn' folder

**Comment by Igloczek** [comment]
It's an issue while using `gulp dev` / `gulp watch` or also while you are trying to manually compile styles with `gulp styles`?

**Comment by cernfortech** [comment]
It's an issue while using gulp watch. 'Gulp styles' works fine but I need to compile styles.scss of 'convert-lanullva' theme even when I'm changing styles in some module-related .scss file. I don't use gulp dev, I'm using Livereload.

**Comment by Igloczek** [comment]
So, unfortunately, it seems to be related to #223 😢

**Comment by cernfortech** [comment]
Okay, np! Then will be waiting for new awesome updates from you and your collaborators :)

**Comment by Igloczek** [comment]
Could you check the solution from #223 released with 1.5.6?

**Comment by cernfortech** [comment]
Hi, I've checked release 1.5.8 and with such module's path config 'convert-lanullva' is compiling great:
"modules": {
      "Convert_ProductSlideIn": "vendor/convert/module-product-slidein/view/frontend"
    }

But if I would add here such module's path:
"modules": {
      "Convert_ProductSlideIn": "vendor/convert/module-product-slidein/view/frontend",
      "Plumrocket_SizeChart": "app/design/frontend/Convert/lanullva/Plumrocket_SizeChart"
    },
'convert-lanullva' theme doesn't compiling by watch-task. Watcher just see that Plumrocket_SizeChart's styles were changed but 'convert-lanullva' theme is not compiled automatically.

PS. Sorry for the belated response!

**Comment by Igloczek** [comment]
Are you sure that you imported partials from `Plumrocket_SizeChart` in your theme or there is a "main" scss file (without leading `_`) in this module?

**Comment by cernfortech** [comment]
Yep, I've executed 'gulp inheritance' and 'Plumrocket_SizeChart' has the same structure as 'Convert_ProductSlideIn' inside 'frontend' folder. I mean 'styles/_module.scss'.

**Comment by Igloczek** [comment]
By "import", I mean sass `@import '../Plumrocket_SizeChart/styles/module';` in your theme `styles.scss`

**Comment by cernfortech** [comment]
Ah yes! There were misspelling in path. Thanks for help and sorry for disturb!

**Comment by Igloczek** [comment]
You're welcome :)
