### ISSUE TITLE
destination directory wrong?

### ISSUE THREAD

**Issue by LeonB** [SnowdogApps/magento2-frontools#236]
``` sh
$ cd vendor/snowdog/frontools
$ gulp styles
[14:35:03] Using gulpfile ~/public_html/vendor/snowdog/frontools/gulpfile.js
[14:35:03] Starting 'styles'...
[14:35:03] Starting 'inheritance'...
[14:35:04] Finished 'inheritance' after 1.79 s
[14:35:05] Theme: japarts styles.css Compiled!
[14:35:05] Finished 'styles' after 2.11 s
$ tree ../../../pub/static/frontend/
../../../pub/static/frontend/
└── Timonline
    └── japarts
        └── nl_NL
            └── home
                └── japarts-motor.com
                    └── public_html
                        └── app
                            └── design
                                └── frontend
                                    └── Timonline
                                        └── japarts
                                            └── styles.css

11 directories, 1 file
```

So the whole absolute paths gets added to the dest path. I would expected the path to be `pub/static/frontend/Timonline/japarts/nl_NL/css/styles.css`.

`console.log(dest)` in `scss.js` shows: `/home/japarts-motor.com/public_html/pub/static/frontend/Timonline/japarts/nl_NL`.

`console.log(srcBase)` shows `/home/japarts-motor.com/public_html/var/view_preprocessed/frontools/frontend/Timonline/japarts`

When requesting that specific css file I get: `Unable to resolve the source file for 'frontend/Timonline/japarts/nl_NL/css/styles.css'`.

`themes.json` looks like:

``` json
{
  "japarts": {
    "src": "app/design/frontend/Timonline/japarts/",
    "dest": "pub/static/frontend/Timonline/japarts",
    "locale": ["nl_NL"],
    "ignore": [".test", "*.tmp", ".fuse_hidden*"]
  }
}
```

Am I doing something wrong? Or is this some kind of bug maybe in combination with our server config?

**Comment by Igloczek** [comment]
1. Are you sure that file structure inside `app/design/frontend/Timonline/japarts` looks good?
2. Are you sure that you don't have any symlinks in places that tools might use for reading or saving stuff?
3. Did you try to remove last `/` from your `src` param in `themes.json`?

**Comment by LeonB** [comment]
@Igloczek , awesome! The trailing slash in themes.json was the problem. Now I'm only into why the pipeline gets triggered when an atomic write is taking place:

``` sh
[11:30:27] Change detected. Theme: japarts File: app/design/frontend/Timonline/japarts/styles/styles.scss.tmp
```

**Comment by Igloczek** [comment]
Great!
Tools are watching all files, any extension. But after detecting change it shouldn't do anything, b/c `tmp` isn't known extension.

**Comment by LeonB** [comment]
I've now changed `watch.js` to:

``` js
    const tempWatcher = plugins.chokidar.watch(themeTempSrc, { // eslint-disable-line one-var
            ignoreInitial: true,
            usePolling: true
          }),
          srcWatcher = plugins.chokidar.watch(themeSrc, {
            ignoreInitial: true,
            ignored: /.*\.tmp$/
          }),
          destWatcher = plugins.chokidar.watch(themeDest, {
            ignoreInitial: true
          });
```

If I don't specify `/.*\.tmp$/` sometimes the compile doesn't get triggered. Maybe something with the timeout?! And I need to set `usePolling` to true for the symlinked files in var/view_preprocessed/frontools. According to the `chokidar` documentation it should follow symlinks but it looks like it doesn't on this (server)configuration ¯\\\_(ツ)\_/¯

Thanks for the help!

**Comment by Igloczek** [comment]
The timeout is only used for reinitialization (to no fire it while you are moving many files at once), so only when you are adding or moving files.
I don't get what's the point with `tmp` files, but I'm happy that you find the solution 😉 
Good advice with `usePolling` param, it may help people in #223 .
