### ISSUE TITLE
Don't lint generated CSS

### ISSUE THREAD

**Issue by Radiergummi** [SnowdogApps/magento2-frontools#239]
While using the `watch` task, I noticed SCSS will be linted, then compiled to CSS, then the CSS will be linted again. Checking the code style of the SCSS output does not make sense.

**Comment by Igloczek** [comment]
It makes sense, b/c `stylelint` check different rules than `sass-lint`.

**Comment by Radiergummi** [comment]
But the CSS code stylelint checks is 100% generated by `sass`, an application I have to trust that it transforms my linted SCSS into completely valid CSS. To conform to the stylelint rules, I'd need to fine-tune the output of SCSS. That, however, doesn't make sense because nobody will open the actual CSS files every again. Any changes are done in the SCSS files.  
After all, linters are there to make sure other people can work with my code easily, right?

**Comment by Igloczek** [comment]
`stylelint` reports issues in you `scss` files using maps, i.e. wrong color definitions, to high specificity, unnecessary rules (i.e. usage of `float` with `inline-block`). 
`sass-lint` just can't report this type of issues.
Check the available rules for both tools and you will understand, that one lint isn't enough.
