### ISSUE TITLE
Add ability to throw "regular" errors from compilation process - useful in CI / CD pipelines

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-frontools#24]

**Comment by timneutkens** [comment]
@Igloczek Could you explain this a bit? I might be able to do this.

**Comment by Igloczek** [comment]
I was thinking about adding [this `ci:` prefixed](https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/gulpfile.js) tasks. In CI / CD pipelines we want to tasks throw regular errors, not only print them in console, b/c our tests/deployment should fail in this case.

It's heavily related to #23.

**Comment by timneutkens** [comment]
Might do that using a `--ci` flag (or something similar) and then checking if it is set, that way we don't have to redeclare all tasks with a prefix.

**Comment by Igloczek** [comment]
Exactly, I just do this on theme lvl, b/c lack of time :wink:

**Comment by timneutkens** [comment]
I'll add it if you want

**Comment by Igloczek** [comment]
That would be great :+1:

**Comment by timneutkens** [comment]
Added in https://github.com/SnowdogApps/magento2-theme-blank-sass/pull/78.
