### ISSUE TITLE
Source maps outputted twice

### ISSUE THREAD

**Issue by adamgilmour** [SnowdogApps/magento2-frontools#246]
Hi, 

I'm having an issue with source maps outputting the styles twice, does anyone else have the same problem?

Example screenshot:
![image](https://user-images.githubusercontent.com/13436050/29515721-6e786d36-8665-11e7-82ab-e0cf2b4a7269.png)

Thanks

**Comment by Igloczek** [comment]
Did you manually check this CSS code? I'm pretty sure there are just two imports of the same file, not "duplicated sourcemap".

**Comment by adamgilmour** [comment]
I've just checked and you are correct - it's outputting the css file twice. The culprit was a default link in the admin panel - content > configuration >default store view > HTML head > 'scripts and stylesheets'

This was set as `<link  rel="stylesheet" type="text/css"  media="all" href="{{MEDIA_URL}}styles.css" />`

I've taken this out and it now uses the default_head_blocks.xml link, setup in the snowdog sass theme.

Thanks
