### ISSUE TITLE
Create port of `setup:static-content:deploy` CLI command

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-frontools#25]
- [x] compile styles - use #22  + `styles` task
- [x] copy necessary files from theme directories (remember about inheritance)
- [ ] copy necessary files from `/lib/web`
- [ ] build require.js config
- [ ] copy and minify(?) `html` templates
- [ ] build `js-translation.json`

**Comment by MattLishman** [comment]
Will this also add running `babel` as part of the deploy task?

**Comment by Igloczek** [comment]
@matthewhaworth not sure yet, but probably this will be set of tasks, not one big task. As I mention in #180, currently `deploy` task isn't so useful at all, expect radical changes soon.

**Comment by AurelienLavorel** [comment]
@Igloczek can we sponsor ($) that issue to have it quicker?
