### ISSUE TITLE
Question: custom destination path

### ISSUE THREAD

**Issue by pascal08** [SnowdogApps/magento2-frontools#253]
My template is located in: `app/design/frontend/MyTheme/theme`

Inside this folder I have `web/css/source` where all my .scss files are located.

Now I want to use Frontools to preprocess these files into .css files in `pub/static/frontend/MyTemplate/theme/en_US/css`. 

Is use this Frontools configuration:

```
{
  "theme": {
    "src": "app/design/frontend/MyTheme/theme",
    "dest": "pub/static/frontend/MyTheme/theme",
    "locale": ["en_US"]
  }
}
```

Using this configuration the output is placed in `pub/static/frontend/MyTheme/theme/en_US/web/css`

Is it possible to tell Frontools to place the output in another folder?

**Comment by Igloczek** [comment]
You need to define  `stylesDir`, check [the example configuration](https://github.com/SnowdogApps/magento2-frontools/blob/master/config/themes.json.sample#L25) for reference.

**Comment by pascal08** [comment]
Thanks! I included `stylesDir`: `web/css/source` in my configuration. Now it works!
