### ISSUE TITLE
Unexpected behaviour: gulp watch

### ISSUE THREAD

**Issue by pascal08** [SnowdogApps/magento2-frontools#254]
I would expect `gulp watch` to watch and preprocess my scss files. It detects changes, but it does not preprocess any files. This is the console output when running `gulp watch`: 

```
[14:30:20] Change detected. Theme: mytheme File: var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/rd-navbar_components/_rd-navbar-nav.scss
```

I tried to debug `watch.js` using the following `console.log`s.

```
      // SASS Compilation
      if (plugins.path.extname(path) === '.scss') {
        Object.keys(sassDependecyTree).forEach(file => {
          console.log(file); // output: xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/grid.scss
          console.log(path); // output: xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/rd-navbar_components/_rd-navbar-nav.scss
          console.log(sassDependecyTree);
          console.log(sassDependecyTree[file]);
          console.log(sassDependecyTree[file].includes(path)) //output: false

          if (sassDependecyTree[file].includes(path)) {
            plugins.helper.sass(gulp, plugins, config, name, file);
          }
        });
      }
```

Obviously it does not preprocess my scss files because the if statement evaluates to false. 

Futhermore I noticed that it appends the extension twice in the sassDependencyTree variable:

```
  'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/style.scss': 
   [ '/xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/style.scss',
     '/xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/__variables.scss.scss',
     '/xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/__mixins.scss.scss',
```

This is my `watcher.json` configuration:

```

{
    "usePolling": true
}
```

I'm going to investigate this further. Any ideas?

NB: I'm using: SnowdogApps/magento2-frontools: v1.5.8

**Comment by Igloczek** [comment]
Your SASS imports are not written in a supported way. Run `gulp sass-lint` and it will yell at you 😉 

Your code looks like `@import '_mixins.scss`, but it should look like `@import `mixins`.

**Comment by pascal08** [comment]
I see. That explains the duplicated extension. 

However my problem still persists. I think I found why it doesn't work the way I expect.

Some of my stylesheets have dependencies with dependencies. For example:

`main.sccs`
```
@import 'grid'
```

`grid.scss`
```
@import 'subgrid'
```

`subgrid.scss`
```
// some scss
``` 

It seems like the dependency tree only goes down one layer. Am I correct?

**Comment by Igloczek** [comment]
It should work, the key is to have the names of files and imports defined properly.

In your example, you should have different file names (partials, files that shouldn't be compiled separetly, needs to have `_` at front):
`main.scss` -> `_grid.scss` -> `_subgrid.scss`

**Comment by pascal08** [comment]
Hmm... I followed your instructions but still no deep tree:

```
  'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/style.scss': 
   [ 'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/style.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/__variables.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/__mixins.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/__fonts.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/__modals.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/__forms.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/__tables.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/__lists.scss',
     'xxx/var/view_preprocessed/frontools/frontend/MyTheme/theme/web/css/source/components/__rd-navbar.scss'
]
```

`styles.scss`
```
@import 'components/_rd-navbar';
```

`components/_rd-navbar.scss`
```
@import "rd-navbar_components/rd-navbar-nav";
```

`components/rd-navbar_components/_rd-navbar-nav.scss`
```
// some scss
```

**Comment by Igloczek** [comment]
Still, something is wrong, b/c you have double `_` at the front of the filename in the tree, so these files don't exist and tools can't parse imports inside.

Change first import to:

`@import 'components/rd-navbar';`

and it should work (remember about not using front `_` in imports at all)

**Comment by pascal08** [comment]
Awesome! It works now. I apologize for bothering you.

**Comment by Igloczek** [comment]
You're welcome :)
