### ISSUE TITLE
Error messages in `gulp setup` are misleading

### ISSUE THREAD

**Issue by tomjepp** [SnowdogApps/magento2-frontools#255]
Hi all,

When running `gulp setup`, the plugin assumes that the only way creating symlinks or files can fail is that if they already exist.

This leads to '<symlink> already exists. Skipped it.' errors when you instead have incorrect permissions!

**Comment by Igloczek** [comment]
You are right, feel free to submit a PR with solution 😉 

Source - https://github.com/SnowdogApps/magento2-frontools/blob/master/task/setup.js
