### ISSUE TITLE
Include scss svg sprite in theme folder

### ISSUE THREAD

**Issue by haelbichalex** [SnowdogApps/magento2-frontools#259]
I want to make a scss sprite with the following `svg-sprite.yml` config:
```
css:
  dest: 'images'
  sprite: 'icons-sprite.svg'
  render: {
    scss: true
  }
  prefix: '.icon-%s'
  dimensions: true
```

My svg file and scss sprite is built correctly, but it's somewhere in the `pub/static` folder.
Is there a proper solution to include the scss file in my themes `styles.scss` without specifying the whole path?

**Comment by Igloczek** [comment]
I never tried to use SVG sprites this way, sorry. 
But for sure any file that should be available on the storefront needs to be loaded from `pub/static`, so at least this part looks good.

**Comment by Igloczek** [comment]
Closing due to lack of updates.
