### ISSUE TITLE
How feasible is cross locale optimization with Gulp? (Avoiding unnecessary compilation.)

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#26]
Magento creates a different directory per locale and runs all the Less processing to generate the CSS files. This is because you can make changes per locale. However my understanding is frequently the only change between locales is in PNG files. That implies redoing Less/Sass etc recompilation per locale is actually a waste of time.

Just wondering how hard to get the tool to compare the input files for one locale to another, and so only do one Less compilation then share with other locales.

(Also open to ideas such as "get the Magento command to do build up directory tree of symlinks to spot such commonality, and symlink output CSS files so its easier for Gulp to see there is only one directory that actually needs processing," or other similar config file.)

We are talking about some of these ideas internally as well, but was curious to see how hard to do at the Gulp end (in which case internal priority might be to make sure Gulp integration in "flip to production" flow is better).

**Comment by Igloczek** [comment]
I can't agree, that changes between locales are related only to images.
In many stores we have custom elements (like currency switcher) or overrides for super long words (like in german)

It's true that we should optimize this process when changes between locales didn't exist (but for know I should manage a way to process them in compilation pipeline, b/c they are just ignored  in Frontools)

I'll look on tech side of this after Developers Paradise 😉

**Comment by Igloczek** [comment]
Done! (more info soon)
