### ISSUE TITLE
Theme is not defined in themes.json

### ISSUE THREAD

**Issue by crantron** [SnowdogApps/magento2-frontools#264]
![screen-shot-2017-11-26-at-5 28 10-pm](https://user-images.githubusercontent.com/3859969/33247092-5525846a-d2d0-11e7-9957-5f075f5b4127.png)

*themes.json*
``` 
{
  "blank": {
    "src": "vendor/snowdog/theme-blank-sass",
    "dest": "pub/static/frontend/Snowdog/blank",
    "locale": ["en_US"],
    "ignore": [".test"]
  },
  "JOHNDOE": {
    "src": "app/design/frontend/Gigasavvy/JOHNDOE",
    "dest": "pub/static/frontend/Gigasavvy/JOHNDOE",
    "stylesDir": "styles",
    "locale": ["en_US"],
    "parent": "blank"
  },
}
```

![screen-shot-2017-11-26-at-5 28 39-pm](https://user-images.githubusercontent.com/3859969/33247193-08b07c24-d2d1-11e7-8877-f9965c3aa7c2.png)

**Comment by crantron** [comment]
![201nlr](https://user-images.githubusercontent.com/3859969/33246991-92b62eac-d2cf-11e7-9243-5749d92c6882.jpg)

**Comment by Igloczek** [comment]
Did you check what themes are processed without using `--theme`?

My first idea - You are probably editing wrong `themes.jaon`, it should be in `dev/tools/frontools/config/themes.json`

**Comment by crantron** [comment]
That was it. Thanks man.
