### ISSUE TITLE
How to run frontools in window commandline

### ISSUE THREAD

**Issue by mrtuvn** [SnowdogApps/magento2-frontools#27]
I already install frontools and magento-scss-blank-theme for test on windows
i can see folder theme in rootmagento/vendor and rootmagento/tools/tasks
But in find how to compile scss file theme. I already set config in /tools/tasks/configs/theme.json

**Comment by Igloczek** [comment]
http://lmgtfy.com/?q=how+to+use+gulp+on+windows
