### ISSUE TITLE
Add option to output maps not inline

### ISSUE THREAD

**Issue by GrimLink** [SnowdogApps/magento2-frontools#275]
Add option to output the CSS(scss/less) & JS maps as .map files instead of inline.
Personal preference is in the same directory as the outputted css.

**Comment by kirmorozov** [comment]
+1 
To enable sourceMaps in production.
Will help alot.

**Comment by Igloczek** [comment]
Production is not for debuging, I'll never add something like this, but also this issue is not about this "feature".

**Comment by kirmorozov** [comment]
SourceMaps as separate files are very usefull in production.
As of now I have sourMaps for all the javascripts, so there is no problem to understand what is wrong in uglified javascript, in production. as well as monitor JS errors with tools like Newrelic.
Same would be great for sass/less,

**Comment by kirmorozov** [comment]
Fellows, please provide feedback about patch.
