### ISSUE TITLE
Error running gulp on node 9.4.0

### ISSUE THREAD

**Issue by LaurensTickles** [SnowdogApps/magento2-frontools#278]
Hello, 

I get the following error when running the frontools gulp file.

```❯ ./node_modules/.bin/gulp inheritance
[15:57:31] Using gulpfile ~/htdocs/VDT/vendor/snowdog/frontools/gulpfile.js
[15:57:31] Starting 'inheritance'...
(node:50643) UnhandledPromiseRejectionWarning: Error: absolute srcpath does not exist
```

Any idea on why this happens?

**Comment by Igloczek** [comment]
Because you didn't read the docs

![](https://i.imgur.com/9HmpeWa.png)

**Comment by Igloczek** [comment]
What Frontools version are you using? If I remember correctly, Node 11.x was never supported, since this is not a LTS relase, and in general it's a version released in 2018.

**Comment by BB-000** [comment]
Hi, it is an old project using version 1.5.8

Anyway I managed to get it building at a normal speed again by reinstalling everything using YARN instead of npm 👍

Cheers
