### ISSUE TITLE
Problem when run task in window

### ISSUE THREAD

**Issue by mrtuvn** [SnowdogApps/magento2-frontools#28]
![screenshot 2016-05-07 14 59 05](https://cloud.githubusercontent.com/assets/1908873/15090993/9bebf31a-1464-11e6-963a-873ac7c94fd6.png)
Run task in my project magento 2. But i can't make it run. Config theme already set up
Did i miss do something?

**Comment by Igloczek** [comment]
Too old node.js version. Use current LTS (v4.4.4)

**Comment by mrtuvn** [comment]
now i get problem sass helpers missing

**Comment by Igloczek** [comment]
Read docs.

> lang - define styles lang want to use for processing i.e. less or scss. Should be same as files extension.
