### ISSUE TITLE
How use this tool

### ISSUE THREAD

**Issue by kauanguesser** [SnowdogApps/magento2-frontools#280]
Hello, someone can explain how use this.. i got stuck here:
**Run yarn or npm install**
If someone can make a short tutorial, I'll be grateful.

I'm using Magento 2.2.2 | WHM/cPanel - CentOs 7.4

**Comment by Igloczek** [comment]
Sorry, but you don't even try to solve it on your own.

Using npm or yarn is like breathing for front-end developers and we are not going try to explain it.

**Comment by Januszpl** [comment]
@kauanguesser google about yarn and npm. Then you will know what is difference and which command to use. Good to learn it and other basics first before jumping to Magento frontend.
