### ISSUE TITLE
Add additional steps to the pipeline, do I have to fork the repo?

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-frontools#281]
I want for example to add https://www.npmjs.com/package/postcss-copy - do I have to work with a fork of the repo or was this use case already preconceived ? 

For example, I can add postcss plugins in the themes.json but how to add them to the node_modules which reside in vendor?

**Comment by Igloczek** [comment]
It's not possible to add more packages without forking.

**Comment by amenk** [comment]
Thanks for the info. I helped myself now with  `vaimo/composer-patches`
