### ISSUE TITLE
special case: Can't build when the theme is in the root folder of the project

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-frontools#282]
I am building the theme standalone

I tried 

  "mytheme": {
    "src": "",

But get

	Message:
	    ../../../var/view_preprocessed/frontools/public/default/home/user/local-workspace/theme.example.de/styles/print.scss
	Error: File to import not found or unreadable: vendor/normalize/lib.
	       Parent style sheet: /home/user/local-workspace/theme.example.de/var/view_preprocessed/frontools/public/default/home/user/local-workspace/theme.example.de/styles/print.scss
		on line 2 of ../../../var/view_preprocessed/frontools/public/default/home/user/local-workspace/theme.example.de/styles/print.scss
	>> @import 'vendor/normalize/lib'; // Normalize.css

The problem seems to be in tools/helper/inheritance-resolver.js:14

**Comment by Igloczek** [comment]
The error is kinda clear, you don't have necessary file(s) to compile styles

In file `styles/print.scss` you have `@import 'vendor/normalize/lib`, but `styles/vendor/normalize/_lib.scss` doesn't exist.
