### ISSUE TITLE
BrowserSync examples

### ISSUE THREAD

**Issue by TKlement** [SnowdogApps/magento2-frontools#29]
Can someone provide a sample "browser-sync.json" that actually works?

My JSON looks like this:
```
{
  "open": "external",
  "host": "banana.tk.local",
  "proxy": "banana.tk.local"
}
```
But when I start gulp with
`gulp dev --theme banana`
and BrowserSync opens a new window then Google Chrome ends with

> Website is not available ... ERR_CONNECTION_CLOSED

**Comment by Igloczek** [comment]
It's not an external URL, so remove `open` param.
Also looks like you don't have to use `host` parameter (you use it wrong way) - [docs](https://browsersync.io/docs/options/#option-host)

For all of my project I just use just `proxy`, sometimes with `browser` param to simplify testing and it's good enough.

**Comment by TKlement** [comment]
I tried it 
without "open", 
without "open" & "host"
but in the end there is nothing to see in the browser.
Without "open" and/or "host" the browser will open a new tab with 
https://localhost:3000/en/

My apache has several sites so I can't use "localhost".
Is it a problem with the apache configuration?

**Comment by Igloczek** [comment]
BS proxing your local page to `localhost:3000` - it's default, proper, behaviour.

AFAIK any URL can be proxied via BS without any specific cobfiguration on server side. 
We use it heavy in Snowdog and nobody have problems.

**Comment by Igloczek** [comment]
I have to recommend to read more about BS itself, b/c looks like you don't get idea how it works.

Also closing this issue, b/c it's not related to Frontools specific things.

**Comment by TKlement** [comment]
My settings are correct. Also my browser-sync.json seems to be fine.
Because now it works.
The only problem I or BS has is that I can't use SSL.
When I change my unsecure & secure baseurl for Magento to "HTTP" BS is working fine.

**Comment by Igloczek** [comment]
Did you try `"proxy": "https://banana.tk.local/"`?
