### ISSUE TITLE
How theme blank sass can generate styles file

### ISSUE THREAD

**Issue by mrtuvn** [SnowdogApps/magento2-frontools#291]
I am kinda curious how theme can get file styles.css
See in module Magento_Theme inside theme. Inside layout i found 
`<css src="css/styles.css" />`

 But i can't found any other place inside theme have file styles. How theme can regenerate this file. Inside folder web of theme doesn't have file css

**Comment by Igloczek** [comment]
http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.html
