### ISSUE TITLE
watch task not working in container

### ISSUE THREAD

**Issue by mrtuvn** [SnowdogApps/magento2-frontools#293]
My stack is phpstorm, ubuntu , docker currently using image of mgtcommerce, magento2 . Workarounds for my local development. I have enable polling to true , setup up my themes and magento themes in config. Created symlink from vendor/frontools to my magento_installation/tools. But now my problem here. When i start gulp watch to expect inject instantly my styles changes apply to browser but I found less files not apply changes. Sometimes changes not apply. Is that a problem of frontools ? Any fix on watch task
Using latest version of frontools

**Comment by Igloczek** [comment]
Frontools do not support LESS files since 1.0.0 and to get browserSync you need to use `gulp dev`.
