### ISSUE TITLE
deploy task with scss/sass throws error

### ISSUE THREAD

**Issue by LeonB** [SnowdogApps/magento2-frontools#3]
When configuring a theme with `lang: sass` this errors gets thrown:

``` sh
$ gulp deploy --theme brusten
[10:01:10] Using gulpfile ~/public_html/tools/gulpfile.js
[10:01:10] Starting 'deploy'...


                                                                                           
  [Magento\Framework\Exception\FileSystemException]                                        
  The "/home/brusten.jetfire.tim-online.nl/public_html/" file doesn't exist or not a file  
                                                                                           


dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]


[10:01:13] 'deploy' errored after 3.44 s
[10:01:13] Error: Command failed: ../bin/magento dev:source-theme:deploy --type=sass --locale=nl_NL --area=frontend --theme=Timonline/brusten css/test


                                                                                           
  [Magento\Framework\Exception\FileSystemException]                                        
  The "/home/brusten.jetfire.tim-online.nl/public_html/" file doesn't exist or not a file  
                                                                                           


dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
```

When using `lang:scss` I get this message:

``` sh
$ gulp deploy --theme brusten
module.js:328
    throw err;
    ^

Error: Cannot find module './helpers/scss'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/brusten.jetfire.tim-online.nl/public_html/tools/gulpfile.js:26:55
    at Array.forEach (native)
    at /home/brusten.jetfire.tim-online.nl/public_html/tools/gulpfile.js:25:16
    at Array.forEach (native)
    at Object.<anonymous> (/home/brusten.jetfire.tim-online.nl/public_html/tools/gulpfile.js:23:29)
    at Module._compile (module.js:410:26)
```

**Comment by Igloczek** [comment]
`deploy` task is designed for `less` based themes, which use `@magento-import`. Custom themes should have static imports inside and don't need symlinks/copy to `pub/static` anymore, just compilation / postprocessing.

I'll improve `deploy` task to inform users of custom themes, that this is not necessary.

**Comment by LeonB** [comment]
@Igloczek ah, great! Didn't know that.

**Comment by Igloczek** [comment]
I recommend reading the readme :smile: 

I'll keep this issue open till fix this little bit buggy behavior.

**Comment by LeonB** [comment]
I think the watch task has a similar issue. The `lang` must be `sass` to load the sass.js module. But the watch task does this: `gulp.watch(theme.src + '/**/*.' + theme.lang, [configs.themes[name].lang + ':' + name + ':' + locale]);`

So it uses `theme.lang` to filter file extensions. What would you recommend to do if you want to use the sass compiler but with scss syntax?

**Comment by Igloczek** [comment]
Oh, I missed that point. I'll swap all names to `scss`.

**Comment by LeonB** [comment]
Great for me. But maybe there are people who'll want to use `.sass` files? Maybe alias sass.js to scss.js so people can choose if they want to use sass or scss syntax?

**Comment by Igloczek** [comment]
I think most of devs stick with `scss` syntax. If someone chose `sass`, can easily duplicate content of `helpers/scss.js` and change extension inside.

**Comment by LeonB** [comment]
I think so too.

**Comment by Igloczek** [comment]
Ok, fixed. Pull version 0.2.1.

**Comment by LeonB** [comment]
Awesome thanks! Is there any way to chat? I don't want to create a new issue for every problem I encounter. Especially if I don't know if something by design or really a bug.

**Comment by Igloczek** [comment]
You can catch me on twitter "@Igloczek".
