### ISSUE TITLE
gulp-cache & gulp-remember

### ISSUE THREAD

**Issue by TKlement** [SnowdogApps/magento2-frontools#30]
How about to extend this awesome tool with caching ability?
At the moment my gulp needs 6,6 seconds with BrowserSync for 16 LESS files.

To speed up this a bit more would be very nice. :-)

**Comment by Igloczek** [comment]
To be honest I'm not going to spend time on optimizing LESS compilation anymore, b/c IMO it's pointless. I don't use LESS in any project, looks like most of devs are also migrating to/already on SASS.

If you are familiar with this extensions and want to invest some time- feel free to create pull requests with your solution of this problem 😉
