### ISSUE TITLE
After Upgrade to 2.2.3

### ISSUE THREAD

**Issue by drdreamm** [SnowdogApps/magento2-frontools#304]
I have the following error after upgrading to 2.2.3 - Any ideas ?
```
[Error running Gulp] Error: ../../../var/view_preprocessed/frontools/frontend/XXX/blank/styles/blocks/_extends.scss

Error: You may not @extend an outer selector from within @media.

You may only @extend selectors within the same directive.

From "@extend .abs-checkout-tooltip-content-position-top-mobile" on line 135 of ../../../var/view_preprocessed/frontools/frontend/XXX/blank/Magento_Checkout/styles/module/checkout/_tooltip.scss on line 1133 of ../../../var/view_preprocessed/frontools/frontend/XXX/blank/styles/blocks/_extends.scss

>>     .abs-checkout-tooltip-content-position-top-mobile {

```

**Comment by Igloczek** [comment]
First of all, it's not a Frontools issue, same as it's not related to the Magento 2.2.3 update.

As you can see, the errors are related to SASS compilation and the error message is very clear "You may not @extend an outer selector from within @media. You may only @extend selectors within the same directive."

If you are using https://github.com/SnowdogApps/magento2-theme-blank-sass theme update to 1.0.5 or 1.1.0, if not, fix it on your own.
