### ISSUE TITLE
Possibility to extend Frontools for compiling `*.vue` files

### ISSUE THREAD

**Issue by marvinhuebner** [SnowdogApps/magento2-frontools#324]
In the commit history i've found a commit where you added `.vue` files to the watcher: https://github.com/SnowdogApps/magento2-frontools/commit/aad13be72dd5ce7865505384f873aabc28f7d54b

Now my question: Is there any "official" way to extend frontools to add a task for compiling `.vue` files, because only to watching if there has a file changes seems not quite useful.

Maybe you could describe if there is a way, to also compile `.vue` files with frontools. This would be great!

Thanks in advance!

**Comment by Igloczek** [comment]
It's not currently possible and to be honest I'm not planning to add it to the Frontools.
Building a process that will work as good as for example Webpack, but in Gulp, will take a lot of time, there is no guarantee it's going to work well (you can check how many problems do people have with the `watch` task) and there are really no benefits in doing it.

I suggest two solutions (we are using both in our projects, but slowly moving from requirejs to webpack):
- Use [require-vuejs](https://github.com/edgardleal/require-vuejs) and load uncompiled *.vue files directly to frontend - the simples solution, no tooling required, but also the slowest in terms of performance
- Setup Webpack - It's the most future proof and feature rich solution, which also gives you the best performance.

**Comment by marvinhuebner** [comment]
@Igloczek thanks for your feedback!

I think then we will go with webpack. Unfortunately we will miss the inheritance feature from frontools, but maybe we do not need this at all in our vue component.

**Comment by Igloczek** [comment]
Yeah, inheritance may be tricky, but still, there is a way to do it writing imports in a clever way (aliases may help a lot) and maybe utilize Vue mixins to extract the core of shared components.
