### ISSUE TITLE
BrowserSync and SCSS compilation for 1 SCSS file not working

### ISSUE THREAD

**Issue by jeroenkosse** [SnowdogApps/magento2-frontools#326]
We use a custom theme based on the blank-sass theme. When we run `gulp styles` or `gulp dev` the files are compiled and we see the correct css files and the theme. When we want to change some css in a scss file the compilation is not running and the browsersync is not called because the file is not changed. When we set the file param to undefined in the scss.js helper file the compilation is running and the browsersync is working. Should this file param be set or should it be `undefined`. when i check the file value the value is the correct changed file. 

Could this be a setting or is this something in the scss.js file that is wrong?

The themes.json looks like this:
```js
{
  "blank": {
    "src": "vendor/snowdog/theme-blank-sass",
    "dest": "pub/static/frontend/Snowdog/blank",
    "locale": ["en_US"],
    "ignore": [".test"]
  },
  "test": {
    "src": "vendor/test/theme-frontend-base-snowdog-v1",
    "dest": "pub/static/frontend/test/base",
    "locale": ["en_US"],
    "parent": "blank"
  },
  "test2": {
    "src": "app/design/frontend/test2/theme",
    "dest": "pub/static/frontend/test2/theme",
    "locale": ["en_US"],
    "parent": "test"
  }
}
```

**Comment by Igloczek** [comment]
What do you mean by 
> When we set the file param to undefined in the scss.js helper

?
I just checked this and works as expected. Could you bring more details about your env? Frontools version, node version, OS, do you use any containers, files synchronization tools etc.

**Comment by Igloczek** [comment]
Closing due to lack of response.
