### ISSUE TITLE
Styles compile - problem with destination pub

### ISSUE THREAD

**Issue by mishunia** [SnowdogApps/magento2-frontools#334]
Hi. I have problem with compile SCSS to pub dest.
When i run `gulp watch --theme myThemeName` then the styles are compiled to the directory with my theme to the `web/css/styles.css` file . Where is the problem? 

My themes.json 
```
{
  "blank": {
    "src": "vendor/snowdog/theme-blank-sass",
    "dest": "pub/static/frontend/Snowdog/blank",
    "locale": ["en_US"],
    "ignore": [".test"]
  },
  "myThemeName": {
    "src": "app/design/frontend/Project/myThemeName",
    "dest": "pub/static/frontend/Project/myThemename",
    "locale": ["pl_PL"],
    "parent": "blank"
  },
```

**Comment by Igloczek** [comment]
Remove `pub/static/frontend/Project/myThemename` directory, probably you have some symlinks created by M core pointing back to the theme source directory.

**Comment by Igloczek** [comment]
Closing due to lack of feedback.
