### ISSUE TITLE
Update dependency: cssnano

### ISSUE THREAD

**Issue by Stevie-Ray** [SnowdogApps/magento2-frontools#336]
Hi @Igloczek,

When running `gulp styles --prod` we get a deprecated warning on our deployment server: 
`Node#moveTo was deprecated. Use Container#append.`

This is a known issue with an older version of `"cssnano": "~3.10.0"` it would be nice to see this dependency updated to v4.

**Breaking changes in v4**
They've dropped support for Node 4, now requiring at least Node 6.9.

Current LTS: 8.12.0

**Comment by Igloczek** [comment]
Thank for tracking down the source of this warning. I need to do some changes regarding cssnano config, so will update it in the next release.
