### ISSUE TITLE
disable chmod

### ISSUE THREAD

**Issue by TKlement** [SnowdogApps/magento2-frontools#34]
Is it possible to change/disable that function that tries to chmod the styles-l.css & styles-m.css?
Since the last magento 2 update I have this errors when I call
`gulp dev --theme banana --maps`

> gulp-notify: [Error running Gulp] Error: EPERM: operation not permitted, chmod ...

The reason is that these files now belong to
www-data

> -rw-rw-r--  1 www-data www-data    1234 Mai 27 08:06 styles-l.css
> -rw-rw-r--  1 www-data www-data    4321 Mai 27 08:06 styles-m.css

So maybe we can disable that chmod action. Unfortunately I can't find it by myself.

**Comment by Igloczek** [comment]
It's some weird Windows behaviour, not problems with this tools. Gulp do nothing with files permissions.

Did you try this -> http://stackoverflow.com/a/24246551?

**Comment by amenk** [comment]
I have the same problem on plain Ubuntu Linux (no vagrant or something!)

**Comment by amenk** [comment]
Okay, for some reason my .css files belonged to www-data - fixed by deleting and recreating them. Sorry for noise.

**Comment by amenk** [comment]
Still the question is, why it tries to run chmod (it was able to write the CSS files - probably due to my ACL configs)

**Comment by Igloczek** [comment]
It's possible that Gulp is saving files with same permissions as user running tasks.
I don't think it's a problem with tools itself, so I'm not going to invest my time on investigating poorly described issue of one user.
Let's track down what caused this weird behavior and try to find out a solution, then I'd be happy to merge it to this repository.
