### ISSUE TITLE
Multiple browser-sync instances for multistore development

### ISSUE THREAD

**Issue by marvinhuebner** [SnowdogApps/magento2-frontools#340]
When I'm working on a magento theme, I usually use browser sync option, especially for the css hot reloading.

In a large project, there we currently working on, I have the problem that I have browser sync only for on store, but I have multiple stores (maybe that's a special thing, but they must be called on a subdomain because there is some magic in the background going on [`b2b.m2test.dev`, `b2c.m2test.dev`...]) where the themes inherit from each other. To see the changes, I have a tab open with the browser-sync proxy, but must reload the other stores manually.

So it would be very handy if there where a possibility to have multiple browser sync instances to proxy different (sub)domains in a multistore project.

**Comment by marvinhuebner** [comment]
I've pushed a PR which would implement something like that. Would be great to get some feedback!

Thanks in advance

**Comment by Igloczek** [comment]
Released in v1.7.0
