### ISSUE TITLE
Styles compile error with "dest" folder different than "pub/static"

### ISSUE THREAD

**Issue by rubenRP** [SnowdogApps/magento2-frontools#347]
Since version > 1.5.13 not compiles styles when destination folder is different than pub/static.

This is my themes.json config file:

`"theme": {
    "src": "app/design/frontend/Vendor/Theme",
    "dest": "app/design/frontend/Vendor/Theme/web/i18n",
    "locale": ["en_US", "es_ES"]
  }`

The folder structure in view_preprocessed seems to be correct:

- view_preprocessed
  - frontools
    - frontend
      - Vendor
        - Theme
          - web
            - i18n
              - theme.xml
              - registration.php
              - theme folders...

The terminal output shows the inheritance task, but not the styles task:

`[09:24:31] Using gulpfile ~/Sites/project-develop-2.2/magento/vendor/snowdog/frontools/gulpfile.js`
`[09:24:31] Starting 'styles'...`
`[09:24:31] Starting 'inheritance'...`
`[09:24:34] Finished 'inheritance' after 2.53 s`
`[09:24:34] Finished 'styles' after 2.55 s`

**Comment by Igloczek** [comment]
Should be fixed in v1.7.0
