### ISSUE TITLE
npm ERR! code ETARGET

### ISSUE THREAD

**Issue by teuma86** [SnowdogApps/magento2-frontools#348]
Good Morning

I am upgrading a Magento 2 website using Frontools from M2.1.0 community to M2.2.7 commerce

I have changed my composer.json file lines
"snowdog/frontools": "^1.5",
"snowdog/theme-blank-sass": "^0.10.1",

TO
"snowdog/frontools": "^1.5",
"snowdog/theme-blank-sass": "^1.0.0",

When I cd to vendor/snowdog/frontools and run "npm install" I am now seeing the following errors

    09:03 $ npm install
    npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
    npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
    npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for node-pre-gyp@undefined
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.

Can you give any guidance to resolve this
Before upgrading the magento / frontools theme version I could run this without an issue.

Thank you

Jamie

**Comment by bartdominiak** [comment]
Try use yarn instead npm (temporary)
`npm i -g yarn`
`yarn` (In vendor/snowdog/frontools)

**Comment by teuma86** [comment]
I was using the latest version. I have reverted the previous version they were using (1.5.11) which appears to work without the above issue.

**Comment by Stevie-Ray** [comment]
@Igloczek @bartdominiak, hi guys.

This bug is very easily fixed by deleting node_modules + npm-shrinkwrap.json and regenerating it. 

Please create a hotfix for this.

**Comment by Igloczek** [comment]
Fixed in 1.7.0

**Comment by huangsiyuan2015** [comment]
> We know about this issue with npm. Use yarn instead npm.
> 
> This should help:
> `npm i -g yarn`
> `rm -rf node_modules && yarn` (In vendor/snowdog/frontools)

thanks, it works for me.
