### ISSUE TITLE
No compilation for email.less

### ISSUE THREAD

**Issue by TKlement** [SnowdogApps/magento2-frontools#35]
I have extended my themes.json with

```
    "files": [
      "css/styles-m",
      "css/styles-l",
      "css/email", <-- NEW
      "css/email-inline" <-- NEW
    ]
```

Also new in my theme are these files

> /vendor/company/magento2-company-theme-company/web/css/source/_email-extend.less
> /vendor/company/magento2-company-theme-company/web/css/source/email.less

_email-extend.less contains
```
.main-content {
  .email-items {
    thead {
      th {
        background-color: orange;
      }
    }
  }
}
```

email.less contains
`@import (reference) '_email-extend.less';
`

Now I start
> gulp watch --theme company 

And ... nothing happens.
What is the correct way to tell gulp to read & compile the _email-extend.less?

**Comment by Igloczek** [comment]
RTFM. Run `gulp deploy`

**Comment by TKlement** [comment]
Thank you for the hint,
but my problem ist still the same.
Gulp always compiles only the email-inline.css and not the email.css.

**Comment by albertoedigital** [comment]
Does any new news on this? I have the same problem.

**Comment by Igloczek** [comment]
Frontools do not support LESS anymore.
