### ISSUE TITLE
How to run stylelint and sass lint on app/design theme only?

### ISSUE THREAD

**Issue by pdenissen** [SnowdogApps/magento2-frontools#357]
Hi there,

How can I run the SASS and CSS listing on my custom theme in `app/design/frontend` only. I want to ignore the parent theme in `vendor`.

I'm trying this in the sasslint config:
```
files:
  ignore:
    - 'vendor/[VENDOR NAME]/**/*.scss'
```

Is it even possible?
Thanks!

**Comment by Igloczek** [comment]
`gulp sasslint --theme your_theme_name` should do the trick for SASS linting.
But there is no way to separate your theme from imported styles on CSS lint level, because it works on compiled CSS.

**Comment by pdenissen** [comment]
@Igloczek Thanks, that works for me.
