### ISSUE TITLE
Node.js 12.13.0 LTS

### ISSUE THREAD

**Issue by Stevie-Ray** [SnowdogApps/magento2-frontools#360]
As of 2019-10-21 Node.js made the transition of Node.js 12.x into Long Term Support (LTS). Please update the package.json to allow engine "<13.0.0" as replied in #351.

**Comment by Igloczek** [comment]
On it, will release the update today.

**Comment by Igloczek** [comment]
It's a bit more work than I expected due to the necessity of migration to Gulp 4.x, but I'm like halfway through.

**Comment by Igloczek** [comment]
12.x support released as [v1.8.0](https://github.com/SnowdogApps/magento2-frontools/releases/tag/1.8.0)
