### ISSUE TITLE
How to deal with CORS and XHR in Browsersync?

### ISSUE THREAD

**Issue by stu177** [SnowdogApps/magento2-frontools#376]
I'm having an issue with CORS preventing an XHR request from loading when running through Browsersync.

From doing a bit of research, it looks like Browsersync doesn't apply rewrite rules or middleware to XHR loads, only HTML directly loaded through Browsersync.

Does anyone have any ideas around this? I've tried bypassing CORS in `.htaccess` and Magento but no luck.

Something that is strange is that I tried adding `x-frame-options` to my `env.php` and for the troublesome request, it has this header twice:

![image](https://user-images.githubusercontent.com/7928209/74327428-1a456a00-4d84-11ea-9f2c-08c47152701d.png)

Not really sure how browsers handle this.

I've thought about running it through nginx on my development environment and trying to override the headers there to add Access-Control-Allow-Origin manually to requests.

Thanks.

**Comment by Igloczek** [comment]
Did you tried this? https://www.browsersync.io/docs/options#option-cors

**Comment by stu177** [comment]
No luck, tried both on and off and doesn't seem to make any change to the XHR request headers. I think the XHR requests are completely ignored by Browsersync and just get passed straight through?

**Comment by Igloczek** [comment]
Can you show the exact implementation of the API calls that are failing while using BS? I'll try to check it on friday.

**Comment by stu177** [comment]
I'm not 100% but I think it's this here:

````js
if (this.quote()['website_id'] !== window.quotation.websiteId) {
    customerData.reload(['quote'], false);
}
````

Inside the customerData object, there is this:

![image](https://user-images.githubusercontent.com/7928209/74330828-4d8af780-4d8a-11ea-92ef-31afebada33f.png)

So that's where the non-Browsersync URL's are coming from, not sure if I can change that as it's from a third-party module.

**Comment by Igloczek** [comment]
Ah, so it's just base M2 code, not a custom implementation.

**Comment by stu177** [comment]
It looks to be this which creates it:

````php
/**
 * Get url for customer data ajax requests. Returns url with protocol matching used to request page.
 *
 * @param string $route
 * @return string Customer data url.
 */
public function getCustomerDataUrl($route)
{
    return $this->getUrl($route, ['_secure' => $this->getRequest()->isSecure()]);
}
````

The object it creates has the non-Browsersync URL for `sectionLoadUrl` and `updateSessionUrl`.

**Comment by Igloczek** [comment]
oh, so it can be easy.

You can create a function that rewrites the pattern in files. You can try with just removing the domain or replacing it with localhost.

```js
    rewriteRules: [
      {
        match: /https:\/\/project-url\.test/g,
        fn: () => ''
      },
      {
        match: /\/\/project-url\.test/g,
        fn: () => ''
      }
    ],
```

**Comment by stu177** [comment]
Doesn't seem to work, I've tried putting it straight into the browser-sync.js, as so:

````js
bsConfig.rewriteRules = [
  {
    match: '/http:\/\/mysite\.localtest\.me/g',
    fn: () => ''
  }
]
````

But still getting the non-Browsersync URL's in the XHR content:

````json
{
    "*": {
        "Magento_Customer/js/customer-data": {
            "sectionLoadUrl": "http\u003A\u002F\u002Fmysite.localtest.me\u002Fcustomer\u002Fsection\u002Fload\u002F",
            "expirableSectionLifetime": 60,
            "expirableSectionNames": ["cart","persistent"],
            "cookieLifeTime": "3600",
            "updateSessionUrl": "http\u003A\u002F\u002Fmysite.localtest.me\u002Fcustomer\u002Faccount\u002FupdateSession\u002F"
        }
    }
}
````

**Comment by Igloczek** [comment]
Try to tweak the regexp, to catch the encoded URLs, bc now it probably just can't find the string to replace.

**Comment by stu177** [comment]
It doesn't seem to match anything inside of that JSON I pasted above, even if I try:

````
{
    match: '/example/g',
    fn: () => ''
},
````

That still doesn't match anything inside of that JSON.

**Comment by stu177** [comment]
Oh dear, it's because I had the match value as a string, not a RegExp.

Well, don't I look like a fool.

The help is much appreciated though, sorry to waste your time :confounded:

**Comment by stu177** [comment]
Is there a way to put that in the browser-sync.json by the way while keeping it as a valid JSON?

Currently, I've put it into the browser-sync.js.

**Comment by Igloczek** [comment]
Unfortunately not 😢
Could you please open an issue to support that config also in form of JS file?

**Comment by stu177** [comment]
Sure, I'll open it up now.
