### ISSUE TITLE
Checkout page broken styles

### ISSUE THREAD

**Issue by stu177** [SnowdogApps/magento2-frontools#378]
On the checkout page, it seems the column width styles are broken, having widths sets to values like 700% and 1500%, resulting in this:

![checkout](https://user-images.githubusercontent.com/7928209/74667061-8b2cbd80-519a-11ea-9c5f-a53abc28db39.png)

Also on this page, the tooltip icons have text next to them for some reason.

Is anyone else having this issue or is just something with my theme setup?

On a slightly separate note, is this theme/ project something that is production ready? I'm trying to decide on whether to go with this theme and toolset for a project but really need the stability of it going forward.

Thanks.

**Comment by Igloczek** [comment]
Sorry, but it's not Frontools related, there is probably some bug in the theme code.
