### ISSUE TITLE
themes.json outside of vendor directory

### ISSUE THREAD

**Issue by timneutkens** [SnowdogApps/magento2-frontools#39]
Don't know if anyone else asked this question, but it seems like a bad practice to edit code in your vendor directory. As far as I know composer will say you edited the package every composer update. Also Magento ignores it by default, so you can't get it into git without editing your .gitignore.

For grunt Magento uses `PROJECTROOT/dev/tools/grunt/configs/themes.js`, so as a solution I was thinking about moving themes.json to `PROJECTROOT/dev/tools/frontools/themes.json` or something similar.

There might be a valid reason why it has to be in the vendor directory so I'm curious about your thoughts on this.

**Comment by Igloczek** [comment]
For now just simplicity of making paths to configurations files, but I know it's not a perfect solutions, b/c requires to make a fork of tools per project, to commit your configuration files.

**Comment by timneutkens** [comment]
Would you be open to a pull request to 'fix' this behaviour? Might be able to create a two step, first look in `PROJECTROOT/dev/tools/frontools/themes.json` then in `config/themes.json` if the first is not found.

**Comment by Igloczek** [comment]
Sure, any contributions are welcome 👍

**Comment by timneutkens** [comment]
Cool :) You're fast at responding btw!

**Comment by timneutkens** [comment]
Fixed in #40. Closing.
