### ISSUE TITLE
Upgrade to dart-sass

### ISSUE THREAD

**Issue by GrimLink** [SnowdogApps/magento2-frontools#397]
Node-sass has been officially marked as deprecated -> https://github.com/sass/node-sass/issues/2952#event-3923481355
This does not mean it will not get any maintenance releases.
But it will not get any new features releases.

**Comment by Igloczek** [comment]
Unfortunately, Dart Sass does not support exactly the same set of syntax features as Node Sass and it will require some changes on the themes level to adjust the code to the new compiler (for example `@extend .button:disabled` doesn't work anymore).

I'll add a feature flag to use Dart Sass, but not set it as default, at least for now.

**Comment by Igloczek** [comment]
Dart Sass support released in v1.10.0
