### ISSUE TITLE
Default values for "src" and "dest" properties?

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#4]
Okay, I have been using it for a bit - some suggested improvements. Creating a separate, clean issue per suggestion.

Here is a theme config I was playing with:

      "kangaroo": {
        "src": "../app/design/frontend/AlanKent/kangaroo",
        "dest": "../pub/static/frontend/AlanKent/kangaroo",
        "locale": ["en_US", "en_AU"],
        "lang": "less",
        "default": true,
        "area": "frontend",
        "vendor": "AlanKent",
        "name": "kangaroo",
        "files": [
          "css/kangaroo2",
          "css/styles-m",
          "css/styles-l",
          "css/email",
          "css/email-inline"
        ]
      },

For the "src" attribute, I am suggesting make it optional, defaulted to `"../app/design" + area + "/" + vendor + "/" + name`. It will always be this pattern, so why rekey all the details twice? Feels redundant. Or change "src" to just point at app/design only so there is no redundancy.

For the "dest" attribute, do similar - maybe change to `"../pub/static"` and have the code append area/vendor/name automatically, as that will *always* be the path structure.

I was always worried of a typing error.

**Comment by Igloczek** [comment]
It's designed for custom themes which don't have to use `deploy ` task. Also removes extra config for composer packages.

Sample config for custom theme:
```json
  "demo": {
    "src": "../vendor/snowdog/theme-frontend-demo",
    "dest": "../pub/static/frontend/snowdog/demo",
    "locale": ["en_US", "pl_PL", "ru_RU"],
    "lang": "scss"
  }

**Comment by alankent** [comment]
Hmmm. I was going to suggest having default values for "src" and "dest" so you can specify the full path (to support your case) but with a default computed value from all the other "name", "vendor" etc attributes, but my hesitancy is hard coding in "../" at the start of the path feels wrong as well - why assume it is in a subdirectory?

Okay, I will put up with the redundancy.  Normally I would not expect to have a module being edited under "vendor", but I can see it can be useful at times.

**Comment by Igloczek** [comment]
`../` is necessary because by default we use `/tools` directory to not override grunt files in root.
You can edit files in any place, but final compilation (i.e. inside CI/CD worker) have to know where is the theme (and for sure this is going to be composer package).

**Comment by alankent** [comment]
Note: It is necessary to be in a subdirectory for now, but we might change grunt in the future (e.g. maybe remove it and make it a separate composer package, especially if there is a better Gulp solution that does the same thing! ;-)

If this code is installed via composer, I guess the paths will change to be ../../ to get up out of the vendor directory. But then there is also the question of where is the configs/theme.json (and tasks/browsersync.js that contains the URL to the web server) are going to be kept. These contain changes local to the project (they will not belong in the vendor/snowdogap/fronttool directory).

**Comment by Igloczek** [comment]
Check `composer.json` config, everything by default are copied to `/tools` folder (via `map`).

Idea of removing Grunt (or any other task runner in future) from core is brilliant, everything should be as small composer module as possible.

Good question... but as long it's single file, to be edited not so often, coping them to module repository, doesn't looks like hard job.

**Comment by alankent** [comment]
Regarding the single file to copy comment, I think it's more about what is in Git and adding complexity to a CICD pipeline process. I assume you put the master file somewhere else in Git, then copy into tools directory (or symlink?) after composer install to overwrite the default file. 

Hmm. npm needs install commands run too after you get your code too doesn't it. So I guess it will require extra steps no matter what...

Maybe you could provide a post install script to run npm install etc, that symlinks the themes config file into the tools directory.

**Comment by Igloczek** [comment]
IMO There is only one problem - saving changes to composer module repository.
I don't get how this is adding complexity to CI/CD process... User can define list of command to use on every run. In our CI it's like:
```yaml
before_script:
  - composer instal
  - cd tools && npm install
```

**Comment by alankent** [comment]
I was trying to remove the extra commands, but I agree. You need it anyway as soon as you put "composer install" there, which makes sense.

How do you expect projects to use your code? Clone and customize, or just add composer dependency and put the package somewhere public? If the latter, the question (which may be what you meant in your comment) is where does each project put their customizations (their own themes.json file I guess? anything else?) so that your module can pick it up.

One example - you add to the the install commands to install the local change afterwards.

    before_script:
        - composer install
        - cd tools && npm install
        - cd tools/configs && mv themes.json themes.json.orig && ln -s ../../my-local-themes.json themes.json

I was wondering if you had something more elegant in mind.

Note that Magento is trying to move all of its stuff out of the root directory and leave it under 'vendor' so its clear what files belong in git and what does not - makes the .gitignore file easier. We don't have that work completed yet, so today we still have all these 'dev' etc directories. So if you wanted to be consistent with Magento long term direction, I would not install the code under 'tools' but rather leave it under 'vendor' with all the other downloaded files. But that is your call. I assume you would document to add "tools" to .gitignore?

**Comment by Igloczek** [comment]
I'm going to try run post install jobs via composer scripts - https://getcomposer.org/doc/articles/scripts.md

> How do you expect projects to use your code?

Fork (per project) -> Customize -> Use
IMO it's simpler and most "composer way".

> So if you wanted to be consistent with Magento long term direction, I would not install the code under 'tools' but rather leave it under 'vendor' with all the other downloaded files.

But it's completely uncomfortable to use... As long as production M2 should have ~ 3 files inside (depends on readme files, build tools configuration etc.), it's easier to ignore everything and exclude this few files, instead digging inside vendor to find everyday use tools.
```
/**/*
!.gitignore
!composer.json
!composer.lock
```
