### ISSUE TITLE
Convert synchronous methods to promises (or something similar)

### ISSUE THREAD

**Issue by timneutkens** [SnowdogApps/magento2-frontools#42]
By converting some methods to promises we might realise a big build speed improvement.
I would be happy to implement this 👍

**Comment by Igloczek** [comment]
Which one? I see that only `deploy` task may run little bit faster (butt all I'm focusing on using SASS and doing processing non-magento way,without using M2 CLI - it's just temporary solution / fallback to LESS users)

**Comment by timneutkens** [comment]
Yeah only the deploy task. Sorry that I wasn't clear, it was late ;) But ok, lets close this one then 👍
