### ISSUE TITLE
Reduce the number of compiled files

### ISSUE THREAD

**Issue by MaxAlekseyev** [SnowdogApps/magento2-frontools#434]
Hello,

FT compile 10 files, but generally fo development I need only one as usual. How can I cotrol this issue?
I can select the theme in cli. I triesd to put the email-fonts.css to ignore block, but no success.
The most perfect way will be tisekect the compilation config but the key, but I'm noy sure that this is available 
without the great headache

![image](https://user-images.githubusercontent.com/10415908/139585155-af1b3266-550c-4ec8-b1ff-b2d94092ccd7.png)

M

**Comment by Igloczek** [comment]
Hi, you can use `watch` task, or `dev` if you also want a BrowserSync running, it will compile only the stuff you changed, without need of doing anything manually.

**Comment by MaxAlekseyev** [comment]
How I can use 

    "ignore": [
      ".test"
    ]

in a right way?

**Comment by Igloczek** [comment]
Ignore is in use just in determining the SASS imports tree, it won't prevent files from being complied.

What is wrong with `watch` stuff, that you want to force the tools to ignore some stuff?

**Comment by MaxAlekseyev** [comment]
I got the project with Frontools but working under Windows, watch is not working correctly

**Comment by Igloczek** [comment]
Did you try to set `usePolling`?

https://github.com/SnowdogApps/magento2-frontools#watcherjson-structure
