### ISSUE TITLE
Add PHP Code Sniffer support

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-frontools#45]
I want to add a PHP Code Sniffer support to watch and check validity of templates live, without using Magento CLI / other ways to trigger them manually.

Check if we have to stick with super old version shipped with M2 - current is 2.6, but M2 use 1.5 (2014)
Same about PHPUnit - current is 5.4, but in M2 we have 4.1 (again 2014)

Links:
https://github.com/sebastianbergmann/phpunit
https://github.com/squizlabs/PHP_CodeSniffer
https://github.com/JustBlackBird/gulp-phpcs

**Comment by timneutkens** [comment]
Cool, big fan of phpcs and phpmd. Actually kinda authored [gulp-phpmd] (https://www.npmjs.com/package/gulp-phpmd-plugin) which uses the same programmatic api as gulp-phpcs.

You just want to integrate the PSR-2 check right?

**Comment by Igloczek** [comment]
I tries to stick with tests build-in in M2, but if PHPMD brings something new / do it better, maybe it's worth to check it.

**Comment by timneutkens** [comment]
It's mainly for code complextion etc, so it might not be relevant for a front-end build. Except when we watch all files ofcourse.

**Comment by timneutkens** [comment]
Just saw a [blog post](https://magento.com/blog/technical/marketplace-extension-quality-program-update) from Magento about coding standards using phpcs. They released it as a seperate package: https://github.com/magento/marketplace-eqp

**Comment by Igloczek** [comment]
I'm still waiting for some response on Magento Community Forum...
https://community.magento.com/t5/Programming-Questions/PHP-Static-tests-for-front-end-devs/m-p/40060
