### ISSUE TITLE
Bower / NPM packages support

### ISSUE THREAD

**Issue by timneutkens** [SnowdogApps/magento2-frontools#46]
Don't know if we would want to support a package manager. But it's certainly something we can have a look at.

[bower.io](http://www.bower.io) with [wiredep](https://github.com/taptapship/wiredep)
[npmjs.com](http://www.npmjs.com) with [browserify](http://browserify.org/), might be some other solution for require.js though.

**Comment by Igloczek** [comment]
Would be nice to load libs to themes this way. If you have some time and feel familiar with this - just do it :)

IMO the npm way looks better lon ong term.

**Comment by timneutkens** [comment]
Yeah npm seems the better solution. Especially from the 'no extra dependency' perspective. I will have a look into it tomorrow.

**Comment by timneutkens** [comment]
Small update on this. Been doing some research into this, came across [jspm](http://jspm.io/) which seems promising because it's based on [systemjs](https://github.com/systemjs/systemjs) the new universal module loader standard. Downside of NPM atm is that it doesn't have great support for front-end stuff like sass, images, fonts etc. jspm provides a layer on top of that and is package manager agnostic, so if the next great npm / bower / etc comes into play there is less hassle.
Don't get me wrong I'm not sold on jspm 😉 would love to use NPM if possible, they are working towards better support for frontend packages with npm3.

**Comment by Igloczek** [comment]
Currently I just know jspm name :laughing: 
Will read about it after #mm16de, next weekend probably - it's not a must have, so can wait a while.

**Comment by timneutkens** [comment]
Indeed.

**Comment by sydekumf** [comment]
Hi guys, what is the current status of providing this repository as npm package?

**Comment by timneutkens** [comment]
Hey,
The package heavily depends on being a composer module at the moment. Also it's focused on Magento2 which uses composer by default. Don't think there is a need to publish it as a npm module.

**Comment by Igloczek** [comment]
That's right, I don't think it makes sense (or even if it's possible) to use it at npm package.

Also this task is about loading 3rd party modules in Frontools via npm / bower, not pushing Frontools to this package managers.

**Comment by sydekumf** [comment]
Okay, sry if I chose the wrong issue :-)
We want to reuse this repository and install it via npm as we heavily use gulp and also this repo uses gulp too. To a npm package would be nice. Otherwise we have to do our own npm package and install it via composer in it which is quite complicated.

**Comment by timneutkens** [comment]
So what you mean is that you don't want to install gulp twice?

**Comment by sydekumf** [comment]
Currently we use package.json and composer.json, only to install frontools via composer. We also wrote a npm module for bootstrapping frontools and its tasks. We copied your bootstrap (your gulpfile.js bootstraping the plugins and configs) and changed to a module. Now every time you change something to your gulpfile.js we have to adopt our bootstrap nmp module. Currently it looks like this and maybe we can push a pull request:

```
'use strict';
// Plugins / Functions / Modules
const gulp    = require('gulp'),
    plugins = require('gulp-load-plugins')({
        pattern: ['*', '!gulp', '!gulp-load-plugins'],
        rename : {
            'browser-sync'    : 'browserSync',
            'fs-extra'        : 'fs',
            'marked-terminal' : 'markedTerminal',
            'postcss-reporter': 'reporter',
            'run-sequence'    : 'runSequence',
            'js-yaml'         : 'yaml'
        }
    }),
    config = {
        'projectPath': plugins.fs.realpathSync('../../') + '/'
    };

module.exports = function (opts, minimistOpts) {
    plugins.errorMessage = require('../../' + opts.dir + '/helper/error-message')(plugins);
    plugins.getThemes = require('../../' + opts.dir + '/helper/get-themes')(plugins, config);
    config.themes = require('../../' + opts.dir + '/helper/config-loader')('themes.json', plugins, config, false);

    // Define task for each theme, locale, lang, processing type etc.
    // Gulp can't run same task in parallel, so we need different names
    Object.keys(config.themes).forEach(name => {
        const theme = config.themes[name];
    theme.locale.forEach(locale => {
        gulp.task(
        theme.lang + ':' + name + ':' + locale,
        require('../../' + opts.dir + '/helper/' + theme.lang)(gulp, plugins, config, name, locale)
    );});});

    return {
        plugins: plugins,
        config: config
    }
};
```

**Comment by Igloczek** [comment]
@sydekumf let's move to #88

**Comment by loganstellway** [comment]
@timneutkens @Igloczek 

I'm not sure if there was a reason for ignoring the `node_modules` folder in `helper/inheritance-resolver.js` when compiling SASS, but I would like to compile some SASS from Node dependencies along with my theme styles. 

I have reworked the paths passed to the **Globby** plugin:
[7637bd1ded060d6584ecf222779dd3fb03d55506](https://github.com/loganstellway/magento2-frontools/commit/7637bd1ded060d6584ecf222779dd3fb03d55506)

Now, I can simply include Node dependencies from my `.scss` file like so:
>@import '../node_modules/bootstrap/scss/bootstrap';

The last thing I need to figure out is if/how I can map to my `node_modules` folder from a `requirejs-config.js` file in my theme.

Thank you guys for the all the awesome work!

**Comment by loganstellway** [comment]
Also for the record, I was able to get `node_modules` Javascript assets to be available via RequireJS. Using Bootstrap as an example, this is what I did inside my theme folder:

1. Required `bootstrap` in `package.json`
2. After installing the dependencies (with `yarn`), I created the symbolic link `Magento_Theme/web/js/node_modules` pointing to `../../../node_modules`
3. Then I created a `requirejs-config.js` file in my theme
```
var config = {
    map: {
        '*': {
            bootstrapAlert: 'Magento_Theme/js/node_modules/bootstrap/js/dist/alert',
            bootstrapButton: 'Magento_Theme/js/node_modules/bootstrap/js/dist/Button',
            bootstrapCarousel: 'Magento_Theme/js/node_modules/bootstrap/js/dist/carousel',
            bootstrapCollapse: 'Magento_Theme/js/node_modules/bootstrap/js/dist/collapse',
            bootstrapDropdown: 'Magento_Theme/js/node_modules/bootstrap/js/dist/dropdown',
            bootstrapModal: 'Magento_Theme/js/node_modules/bootstrap/js/dist/modal',
            bootstrapPopover: 'Magento_Theme/js/node_modules/bootstrap/js/dist/popover',
            bootstrapScrollspy: 'Magento_Theme/js/node_modules/bootstrap/js/dist/scrollspy',
            bootstrapTab: 'Magento_Theme/js/node_modules/bootstrap/js/dist/tab',
            bootstrapTooltip: 'Magento_Theme/js/node_modules/bootstrap/js/dist/tooltip',
            bootstrapUtil: 'Magento_Theme/js/node_modules/bootstrap/js/dist/util'
        }
    }
};
```

**Comment by Igloczek** [comment]
@loganstellway version 1.3.0 doesn't ignore node_modules directory anymore. But I'm still thinking about future of this feature. 

I have in mind idea similar to `map` option in RequireJS config, where we can map any path to some user-friendly name and then use across the project.

In our case, it will symlink these files to `var_viewprocessed` directory, not into `node_modules` directory, but to defined in `map` path. 

So we will be able to easily define that `node_modules/bootstrap/bootstrap.scss` is our `Magento_Theme/styles/bootstrap.scss`. Ofc this will work with all file types.

What do you think about it?

**Comment by loganstellway** [comment]
@Igloczek - I have upgraded and it is working great, thank you! 

My thoughts on the JS assets:

The assets in the `styles` directory of a theme are being dropped into the `css` directory of the theme's `pub/static` directory - I think it would make sense to place any JavaScript assets into a `js` folder in the theme's `pub/static` directory. 

I think it would be great if Frontools had the ability to read a theme's `requirejs-config.js` file to figure out what `.js` files it needs to copy to the `pub/static` directory. 

The `requirejs-config.js` file is just a JavaScript file that seems to be copied into an auto-executing function inside of a theme's merged `requirejs-config.js` file:
```
(function() {
    var config = {
        map: {
            '*': {
                'wpRest': 'Gigasavvy_WpRestAPI/js/main'
            }
        }
    };
    require.config(config);
})();
```

Not sure if there could be some variable that indicates that the defined path or mapped file needs to be copied from a theme's `node_modules` folder. Something like:
```
var node_modules = 'js'; // Will point Magento to the "js" folder created by Frontools
var config = {
    'paths': {
        'bootstrap': node_modules + '/bootstrap/js/dist'
    },
    'map': {
        '*': {
            'slick': node_modules + '/slick-carousel/slick/slick.min'
        }
    }
};
```

**Comment by loganstellway** [comment]
@Igloczek - I have upgraded and it is working great, thank you! 

I think the symbolic links are great for `.scss` assets and the Frontools workflow for compiling styles with SASS.

My thoughts regarding **JS** assets:

The assets in the `styles` directory of a theme are placed in a `css` directory of the theme in the `pub/static` folder - I think it would make sense to place JavaScript assets in a `js` folder in a theme's `pub/static` directory. 

I think it would be great if Frontools had the ability to read a theme's `requirejs-config.js` file to figure out what `.js` files it needs to copy to the `pub/static` directory. 

I'm wondering if Frontools can
  - Iterate through the `config` variable of the `requirejs-config.js` in a theme
  - Check if the item begins with `js/`
  - If so, check if a `node_modules` folder exists and if a corresponding file or path exists there
  - Copy it to the `destPath`

So for:
```
var config = {
    'paths': {
        'bootstrap': 'js/bootstrap/js/dist'
    },
    'map': {
        '*': {
            'slick': 'js/slick-carousel/slick/slick.min'
        }
    }
};
```

(Pseudo code) Do:
```
// Define path to look for "node_modules" folder
var node_path = srcPath + 'node_modules/'

// If "node_modules" folder exists
if ( plugins.fs.existsSync(node_path) ) {
    // Loop through config object (simplified to just "paths" object for example)
    for (var i in config['paths']) {
        // Current item
        var path = config['paths'][i];

        // If item begins with "js/"
        if (path.indexOf('js/') === 0) {
            // Define item path in "node_modules" folder
            var node_asset = node_path + path.replace('js/', '');

            // If the asset exists
            if ( plugins.fs.existsSync(node_asset) ) {
                // Copy from location in "node_modules" folder to "pub/static" theme folder
                copyJsAsset(node_asset, destPath + path);
            }
        }
    }
}
```
