### ISSUE TITLE
Add a setup command

### ISSUE THREAD

**Issue by timneutkens** [SnowdogApps/magento2-frontools#47]
Maybe it's good to combine all installation steps into a `gulp setup` task. What it will have to do:

- [x] Symlink directory using the current symlink task
- [x] Copy the config json files to: <project root>/dev/tools/frontools/configs/themes.json. We will only want to do this when they are not already there

We might ask for the browsersync proxy url to automatically set it.

**Comment by Igloczek** [comment]
To be honest much more important thins hangs on board, so this and github pages have super low priority for me.

If you have time to do this - feel free.

**Comment by timneutkens** [comment]
Yeah it's just small improvements. Will do this myself. Just checking if you're alright with it 😉
