### ISSUE TITLE
Create a proper github pages page

### ISSUE THREAD

**Issue by timneutkens** [SnowdogApps/magento2-frontools#48]
Just because we can 😉

**Comment by timneutkens** [comment]
Doesn't have priority. Will do this myself when I have spare time.

**Comment by Igloczek** [comment]
I just rethink this idea and I though it isn't necessary to have this type of page for this project - it's too small.

**Comment by timneutkens** [comment]
Yeah I agree, was just one of the things that came to mind at the time.
