### ISSUE TITLE
How to support dependencies per Less file?

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#5]
First, here is my configuration for reference.

      "kangaroo": {
        "src": "../app/design/frontend/AlanKent/kangaroo",
        "dest": "../pub/static/frontend/AlanKent/kangaroo",
        "locale": ["en_US", "en_AU"],
        "lang": "less",
        "default": true,
        "area": "frontend",
        "vendor": "AlanKent",
        "name": "kangaroo",
        "files": [
          "css/kangaroo2",
          "css/styles-m",
          "css/styles-l",
          "css/email",
          "css/email-inline"
        ]
      },

css/kangaroo2 is a .less file in the theme. When I touch this file, all of the Less files are recompiled. This is slow.

How do you suggest I achieve something like the following?

- For `css/styles-l` watch `css/styles-l.less` and `**/_*.less`.
- For `css/styles-m` watch `css/styles-m.less` and `**/_*.less`.
- For `css/email` watch `css/email.less` and `**/_*.less`.
- For `css/email-inline` watch `css/email-inline.less` and `**/_*.less`.
- For `css/kangaroo2` watch `**/*.less`.

The first four could be merged in practice, because they all depend on the same files. So if one changes, they will all probably need recompiling. But it is important (for speed) that changes to `kangaroo2.less` DO NOT trigger the first 4 to recompile (and hence the `**/_*.less` rule - only things with leading underscore will trigger those files to recompile).

I actually don't care which way its achieved, but being able to change `kangaroo2.less` without compiling the other files is the important part. It goes from say 10 seconds to under 1 per file change - much nicer experience. Maybe need to be able to specify watch dependencies per file?

**Comment by Igloczek** [comment]
Hm, `kangaroo2.less` don't use any imports? Should, because like any other styles depend on Magento UI and theme variables/overrides.

And we are back in idea of digging into files to find imports, build relation tree, just to handle too heavy LESS theme.

**Comment by alankent** [comment]
Kangaroo2.less uses only one or two imports, not hundreds like the other 4 files (due to the //@magento_import expansion magic). So it is much faster.

I am suggesting here I manually type in the dependencies - nothing automatic. (That is why I created the separate issue from #1.) I had this running with my Gulpfile and it works pretty well in practice. E.g.

      "kangaroo": {
        "src": "../app/design/frontend/AlanKent/kangaroo",
        "dest": "../pub/static/frontend/AlanKent/kangaroo",
        "locale": ["en_US", "en_AU"],
        "lang": "less",
        "default": true,
        "area": "frontend",
        "vendor": "AlanKent",
        "name": "kangaroo",
        "files": {
          "css/kangaroo2": ["**/*.less"],
          "css/styles-m": ["css/styles-m.less", "**/_*.less"],
          "css/styles-l": ["css/styles-l.less", "**/_*.less"],
          "css/email": ["css/email.less", "**/_*.less"],
          "css/email-inline: ["css/email-inline.less", "**/_*.less"]
        }
      },

**Comment by Igloczek** [comment]
`"**/*.less` will watch all less files, even that with `_` at front, but if you don't care about any imports you can watch this single file, so config might looks like this:

```json
    "files": {
      "css/kangaroo2": "single",
      "css/styles-m",
      "css/styles-l",
      "css/email",
      "css/email-inline"
    }
```
But still this just idea of overriding messy/heavy theme, which can leads to e.g. 20 "single" less files in root of styles path, instead of longterm improvement and bigger idea of maintaining extension/changes.
I like to call similar methods as "YOLO methodology" :smile:

**Comment by alankent** [comment]
As you talk about pointing at different directories for src and dest etc, there are also different ways to use the Less files.

The Magento UI Library files all start with a leading underscore, which is why the _*.less rule exists. The Magento UI Library files are shipped by us - sites should not touch them unless they do a composer update. But there is the _theme.less and _extends.less files (in modules) that may be sometimes changed, so I found it useful to include the extra watch rules.

Right now, I have a way to get Gulp working with M2.0 without change to the product. You generate separate extra CSS files and turn on the "file merge" button. The suggested rules will work both if you edit _extends.less (the "old" recommended way), _theme.less (used by themes), or the local Less file ("new" way). In practice the rules are easy to type in and work pretty well.

Stage 2 is to use Less to merge all the CSS files. I think that should work, but have not tried it. It involves adding a new `<head><css>` rule pointing at the merged file and removing the old CSS file references using `<head><remove>` rules in the theme. Again, I think possible with zero change to the product (it is just a different recommendation on *how* to use the product).

Doing a more radical change of how to do styles etc is not a short term task. That would require core product changes, which raises all sorts of backwards compatibility issues. So I am trying to have a "nice" solution that solves a fair bit of short term pain. I will then probably let it sit for a while, get a few community people using it, gather some feedback etc.  I think the watch capability is the last missing bit before I could suggest it as a "good complete solution for M2.0 today". If that goes in, I will throw away what I have done.

I hope that makes sense!

**Comment by alankent** [comment]
Bottom line if you ignore all the detail above - it is useful to be able to specify the dependencies to trigger recompilation of a source file. Recompiling everything on any file change can lead to unnecessary recompilation of Less files. Files like styles-l.less take around 10 seconds on my laptop, so it is a noticeable saving of not recompiling styles-l.less if no changes affecting the file have been made.

(Yes, I am keen ;-) - this is the last thing stopping my adoption of these scripts and discarding my own. Moving the hard coded string "m2test.dev" from tasks/browsersync.js to a configuration file would be another bonus, but not a showstopper.)

**Comment by Igloczek** [comment]
Ok, I'll look on this, but I want to make this little bit more abstract, to use this with wider spectrum of languages, not only LESS (hope this will work, at least, with SASS)

Merging files on Magento level works good enough and might be good to keep unmerged files for HTTP/2.

I get you point of keeping backward compatibility, regardless of current possibility to get themes more dirty, but to make theming for M2 little bit more useful (modularity, independence of modules, tools performance etc.), we need a "bigger idea" and I just write my suggestions and fears about your temporary solutions ;)

**Comment by alankent** [comment]
Thanks. I am particularly interested in tools like Gulp, getting the next step out there, then get lots of eyes looking at it to see if we can make another step of improvement after that. If we have a tool (like Gulp) making it easier for a project to do both, it gives a possible migration path.

FYI: I am working on a blog post right now regarding a suggested development environment, and was going to include this module in it. V1 does not have to be perfect, but let me know when you get close to completion as I may delay publishing until I have that code, rather than posting an errata.

Thanks again for all your effort here by the way. I think this is going to be pretty cool!

**Comment by Igloczek** [comment]
I think up to 2-3 days, but depends on my regular work (if smth don't just blow up ofc :smile: ).

**Comment by Igloczek** [comment]
Okay, I did this :smile:
Imports dependency tree builds fine and it's fast enough, watching and compiling styles works as expected, but I got some node warnings about memory leaks :cry: (no idea why, will look on this soon)

But for now I released version `0.3.0` with "clever watching".

**Comment by alankent** [comment]
Cool bananas! Did you have a sample themes.config file showing how to use it? Or is it all automagical? (I noticed code changes, but no change to themes.json.)

**Comment by Igloczek** [comment]
"Automagical" :)

**Comment by Igloczek** [comment]
Memory leaks fixed. Files compilation woks not exactly as I want to - fixed.

BTW. @alankent - I moved browser-sync config to separate file, enjoy :)
