### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by timneutkens** [SnowdogApps/magento2-frontools#53]
Would like to clean up our code a bit using one of these coding standards:
https://github.com/rwaldron/idiomatic.js or http://standardjs.com/index.html

I don't have a personal preference at the moment. Have used standard.js before but idiomatic.js seems promising, it's a much broader specification for writing javascript.

Both have support for eslint.

**Comment by timneutkens** [comment]
For reference: Addy Osmani has a great article about javascript style guides: https://addyosmani.com/blog/javascript-style-guides-and-beautifiers/

**Comment by timneutkens** [comment]
@Igloczek any thoughts on this?

**Comment by Igloczek** [comment]
Sorry, I'm al little bit bussy now. Let you know ASAP, have to check this, b/c unfortunately I'm not familiar with any of them.

**Comment by timneutkens** [comment]
Sure, doesn't have high priority. FYI I'm starting to lean more towards idiomatic.js, seems like it's a much more mature standard.

**Comment by Igloczek** [comment]
Idiomatic seems like bit more "standard" for me, but description of rules kinda sucks.
At all this topic is related to add some automated testing... have to think about this.

**Comment by timneutkens** [comment]
There is an up to date eslint config for idiomatic.js available here: https://www.npmjs.com/package/eslint-config-idiomatic

**Comment by Igloczek** [comment]
Yup, I know. Just for code style guide testing we can use even https://houndci.com/, but it's just part of really useful tests.

**Comment by timneutkens** [comment]
The amount of new CI systems is astonishing. Never heard of that one. It seems fine but maybe too specific use case to be a good CI.
