### ISSUE TITLE
"clean" rule is a bit too aggressive

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#6]
The `gulp clean` rule currently does a `rm -rf pub/static`. The problem is for Apache users there is a `.htaccess` file in pub/static that is being deleted as well - so after running clean, things stop working. (URL rewrites get turned off.)  There is also a _requirejs directory there.

I am not sure what to replace it with - I used to rm -rf the created directories - the opposite of deploy.

**Comment by Igloczek** [comment]
Fixed, pull `0.2.2`.
