### ISSUE TITLE
Can't execute any command using frontools 0.11.1

### ISSUE THREAD

**Issue by Bartlomiejsz** [SnowdogApps/magento2-frontools#64]
After fresh installation I was trying to execute `gulp setup` command, as in tutorial. 
Unfortunately, it return error, because `plugins`, and `config` consts were undefined. 

I successfully executed this command after replacing declarations of those consts with content from gulpfile.js, but now when I'm trying with `gulp deploy` it also returns following errors:

![2016-07-29_16h17_52](https://cloud.githubusercontent.com/assets/9566840/17251212/042267b4-55a8-11e6-8bfa-c083cff3efb1.png)

Previous errors were almost exactly same.
Am I doing something wrong?

**Comment by Igloczek** [comment]
Thanks for report, I'll check this soon.

**Comment by Igloczek** [comment]
Fixed in 0.11.2 - thanks for report!
