### ISSUE TITLE
Install magento2-frontools without composer

### ISSUE THREAD

**Issue by refaelgold** [SnowdogApps/magento2-frontools#68]
Hey,Where should i put this folder if i not install magento2 frontools via composer?

**Comment by refaelgold** [comment]
magento2ce/dev/tools this is the path that i need to put the repo ? i just want to be sure

**Comment by Igloczek** [comment]
Via composer will be a lot easier, but... tools should works in any place, but have in mind that `projectPath` variable, takes by default vaule of `../../`, so if you want to place this in other location, especially on different "level", have to edit them to fit you needs.

PS. This is a place mostly for issues, not questions about usage. Next time please go to Magento Community Forum - you can find URL in docs.

**Comment by refaelgold** [comment]
allrdy did - thanks
