### ISSUE TITLE
Add gulp-debug

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-frontools#85]
Can you add a --debug switch to debug, for example, less configuration - using gulp-debug?

https://www.npmjs.com/package/gulp-debug

**Comment by Igloczek** [comment]
I'm not going to invest more time on things related to LESS processing. If you have some time to invest, I'm open to any pull requests.
I'm not sure what kind of additional information will be returned, b/c tools use `gulp-logger` and you will be reported about compiled files (AFAIK I try package proposed by you, but `logger` works better).

**Comment by amenk** [comment]
Okay, thanks :-)
