### ISSUE TITLE
Display error if theme directory is wrong / 0 files found

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-frontools#86]
I had a typo in a theme folder name and did not notice :-)

**Comment by Igloczek** [comment]
C'mon, it's a developer oriented set of tools 😉

**Comment by amenk** [comment]
Still developer's like comfort ... really .. :) If you use the tool the first time, you are confused because you don't know if it works or not ...

**Comment by Igloczek** [comment]
I hope that everyone can use `pwd` and simply check sample config to understand how it should looks like.

**Comment by amenk** [comment]
Okay, I can understand you do not want to invest time on this - but still I think such a feature makes sense. Maybe I implement it some day :-)
i.e. if I type "make love" it also says "no rule to make target ..." and does not silently do nothing...
