### ISSUE TITLE
[debugging] browser-sync Reload is not working + inheritance from parent theme

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-frontools#87]
If I read the code correctly, the browser should reload after LESS files are processed.
But it does not.

But browser sync states 

    [BS] Browser Connected: Chrome, version: 52.0.2743.116

**Comment by Igloczek** [comment]
Are you sure that you have CSS merging disabled?

**Comment by amenk** [comment]
yes it is disabled. Is it right to point the `src` also to `pub/static` ? maybe it's related to that? See http://magento.stackexchange.com/a/135732/81 for my config

**Comment by Igloczek** [comment]
Nope, you have to point to real source directory (`app/design..` or composer package in `vendor`, b/c in `pub` you have different folder structure.

Hint: Remove unnecessary themes from themes config if you don't use it.

**Comment by amenk** [comment]
Not working then... beware: I have only _*.less files in my theme - everything else it is inheriting. I think the fall back does not work properly.

<details>
	{
		"blank": {
		  "src": "vendor/magento/theme-frontend-blank",
		  "dest": "pub/static/frontend/Magento/blank",
		  "locale": [
		    "en_US"
		  ],
		  "lang": "less",
		  "default": true,
		  "area": "frontend",
		  "vendor": "Magento",
		  "name": "blank",
		  "files": [
		    "css/styles-m",
		    "css/styles-l",
		    "css/email",
		    "css/email-inline"
		  ]
		},
		"proofxxxx": {
		  "src": "app/design/frontend/Proofxxxx/default",
		  "dest": "pub/static/frontend/Proofxxxx/default",
		  "locale": [
		    "de_DE"
		  ],
		  "parent": "blank",
		  "lang": "less",
		  "area": "frontend",
		  "vendor": "Proofxxxx",
		  "name": "default",
		  "files": [
		    "css/styles-m",
		    "css/styles-l"
		  ]
		}
	}

</details>

**Comment by amenk** [comment]
console.log(plugins.browserSync.active); prints "false" in styles.js, line 7 ... what does that mean?

**Comment by Igloczek** [comment]
You have to run `gulp deploy` before you can compile you LESS files (and every time you add a new LESS file or change main LESS file - without `_` on front) - it will create a symlink to your source directory files inside `pub/static`.

To get working inheritance you need main LESS file in your child theme (`styles.less`), only partials are inherited.

Sample output:
`gulp deploy`
```
➜  tools git:(master) ✗ gulp deploy
[19:36:46] Using gulpfile ~/Sites/magento2/vendor/snowdog/frontools/gulpfile.js
[19:36:46] Starting 'deploy'...
[19:36:59] Finished 'deploy' after 13 s
```
`gulp styles`
```
➜  tools git:(master) ✗ gulp styles --theme backend
[19:37:13] Using gulpfile ~/Sites/magento2/vendor/snowdog/frontools/gulpfile.js
[19:37:13] Starting 'styles'...
[19:37:13] Starting 'less:backend:en_US'...
[19:37:15] Finished 'styles' after 1.37 s
[19:37:16] Theme: backend Locale: en_US styles-old.css Compiled!
[19:37:19] Theme: backend Locale: en_US styles.css Compiled!
[19:37:19] Finished 'less:backend:en_US' after 5.44 s
```

`gulp dev`
```
➜  tools git:(master) ✗ gulp dev --theme backend
[19:47:56] Using gulpfile ~/Sites/magento2/vendor/snowdog/frontools/gulpfile.js
[19:47:56] Starting 'dev'...
[19:47:56] Starting 'browser-sync'...
[19:47:57] Finished 'browser-sync' after 578 ms
[19:47:57] Starting 'watch'...
[19:47:57] Finished 'watch' after 291 ms
[19:47:57] Finished 'dev' after 889 ms
[BS] Proxying: http://magento2.dev
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.43.83:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.43.83:3001
 --------------------------------------
[19:48:08] Theme: backend Locale: en_US styles.css Compiled!
[BS] 1 file changed (styles.css)
[...]
```

**Comment by Igloczek** [comment]
Did you run `browser-sync` task separately or use `dev` task?

**Comment by amenk** [comment]
I ran it separately - thank you very much for your sample workflow.

With `    "src": "pub/design/frontend/Proofgigant/default",`:

	self@self-laptop:~/mestrona/workspace/proofxxxx.de/tools$ gulp deploy
	[19:59:03] Using gulpfile ~/mestrona/workspace/proofxxxx.de/vendor/snowdog/frontools/gulpfile.js
	[19:59:03] Starting 'deploy'...
	[19:59:04] Finished 'deploy' after 1.08 s
	self@self-laptop:~/mestrona/workspace/proofxxxx.de/tools$ gulp styles --theme proofxxxx
	[19:59:19] Using gulpfile ~/mestrona/workspace/proofxxxx.de/vendor/snowdog/frontools/gulpfile.js
	[19:59:19] Starting 'styles'...
	undefined
	[19:59:19] Starting 'less:proofxxxx:de_DE'...
	[19:59:20] Finished 'styles' after 1.15 s
	[19:59:20] Finished 'less:proofxxxx:de_DE' after 846 ms
	self@self-laptop:~/mestrona/workspace/proofxxxx.de/tools$ gulp dev --theme proofxxxx
	[19:59:28] Using gulpfile ~/mestrona/workspace/proofxxxx.de/vendor/snowdog/frontools/gulpfile.js
	[19:59:28] Starting 'dev'...
	[19:59:28] Starting 'browser-sync'...
	[BS] [debug] -> Starting Step: Finding an empty port
	[19:59:28] Finished 'browser-sync' after 351 ms
	[19:59:28] Starting 'watch'...
	[19:59:28] Finished 'watch' after 72 ms
	[19:59:28] Finished 'dev' after 432 ms
	[BS] [debug] Found a free port: 3002
	[BS] [debug] Setting Option: port - 3002
	[BS] [debug] +  Step Complete: Finding an empty port
	[BS] [debug] -> Starting Step: Getting an extra port for Proxy
	[BS] [debug] +  Step Complete: Getting an extra port for Proxy
	[BS] [debug] -> Starting Step: Checking online status
	[BS] [debug] Resolved www.google.com, setting online: true
	[BS] [debug] Setting Option: online - true
	[BS] [debug] +  Step Complete: Checking online status
	[BS] [debug] -> Starting Step: Resolve user plugins from options
	[BS] [debug] +  Step Complete: Resolve user plugins from options
	[BS] [debug] -> Starting Step: Set Urls and other options that rely on port/online status
	[BS] [debug] Setting multiple Options
	[BS] [debug] +  Step Complete: Set Urls and other options that rely on port/online status
	[BS] [debug] -> Starting Step: Setting Internal Events
	[BS] [debug] +  Step Complete: Setting Internal Events
	[BS] [debug] -> Starting Step: Setting file watchers
	[BS] [debug] +  Step Complete: Setting file watchers
	[BS] [debug] -> Starting Step: Merging middlewares from core + plugins
	[BS] [debug] Setting Option: middleware - List []
	[BS] [debug] +  Step Complete: Merging middlewares from core + plugins
	[BS] [debug] -> Starting Step: Setting the rewrite rules given in initial options
	[BS] [debug] +  Step Complete: Setting the rewrite rules given in initial options
	[BS] [debug] -> Starting Step: Setting the rewrite rules middleware for snippet
	[BS] [debug] +  Step Complete: Setting the rewrite rules middleware for snippet
	[BS] [debug] -> Starting Step: Starting the Server
	[BS] [debug] Proxy running, proxing: http://proofxxxx.de.mestrona.localhost
	[BS] [debug] Running mode: PROXY
	[BS] [debug] +  Step Complete: Starting the Server
	[BS] [debug] -> Starting Step: Adding serve static middlewares
	[BS] [debug] +  Step Complete: Adding serve static middlewares
	[BS] [debug] -> Starting Step: Starting the HTTPS Tunnel
	[BS] [debug] +  Step Complete: Starting the HTTPS Tunnel
	[BS] [debug] -> Starting Step: Starting the web-socket server
	[BS] [debug] Setting Option: clientEvents - List [ "scroll", "scroll:element", "input:text", "input:toggles", "form:submit", "form:reset", "click" ]
	[BS] [debug] +  Step Complete: Starting the web-socket server
	[BS] [debug] -> Starting Step: Adding the HTTP protocol
	[BS] [debug] +  Step Complete: Adding the HTTP protocol
	[BS] [debug] -> Starting Step: Starting the UI
	[BS] [debug] Setting Option: session - 1473616769009
	[BS] [UI] Starting Step: Setting default plugins
	[BS] [UI] Step Complete: Setting default plugins
	[BS] [UI] Starting Step: Finding a free port
	[BS] [UI] Step Complete: Finding a free port
	[BS] [UI] Starting Step: Setting options also relevant to UI from BS
	[BS] [UI] Step Complete: Setting options also relevant to UI from BS
	[BS] [UI] Starting Step: Setting available URLS for UI
	[BS] [debug] Getting option via path: urls
	[BS] [UI] Step Complete: Setting available URLS for UI
	[BS] [UI] Starting Step: Starting the Control Panel Server
	[BS] [UI] Using port 3003
	[BS] [UI] Step Complete: Starting the Control Panel Server
	[BS] [UI] Starting Step: Add element events
	[BS] [UI] Step Complete: Add element events
	[BS] [UI] Starting Step: Registering default plugins
	[BS] [debug] Getting option via path: urls,external
	[BS] [UI] Step Complete: Registering default plugins
	[BS] [UI] Starting Step: Add options setting event
	[BS] [UI] Step Complete: Add options setting event
	[BS] [debug] +  Step Complete: Starting the UI
	[BS] [debug] -> Starting Step: Merge UI settings
	[BS] [debug] Setting Option: urls - Map { "local": "http://localhost:3002", "external": "http://192.168.178.35:3002", "ui": "http://localhost:3003", "ui-external": "http://192.168.178.35:3003" }
	[BS] [debug] +  Step Complete: Merge UI settings
	[BS] [debug] -> Starting Step: Init user plugins
	[BS] [debug] Setting Option: userPlugins - 
	[BS] [debug] +  Step Complete: Init user plugins
	[BS] Proxying: http://proofxxxx.de.mestrona.localhost
	[BS] Access URLs:
	 ---------------------------------------
		     Local: http://localhost:3002
		  External: http://192.168.178.35:3002
	 ---------------------------------------
		        UI: http://localhost:3003
	 UI External: http://192.168.178.35:3003
	 ---------------------------------------
	[BS] Browser Connected: Chrome, version: 52.0.2743.116
	[BS] Browser Connected: Chrome, version: 52.0.2743.116
	[BS] Browser Connected: Chrome, version: 52.0.2743.116


:.. I change `my _theme.less` - nothing happens

**Comment by amenk** [comment]
If I use the blank theme with the above workflow it works better ... it detects changes and the browser flickers (I guess that is the reloading - did not manage to switch the Magento theme due to some other backend bug in the moment). But for my child theme ... nothing ... I also debugged yesterday as much as I could into the less task, and it just does not collect any files from my theme. The glob there is excluding `_*` - but my theme only contains files starting with `_`!

**Comment by Igloczek** [comment]
Theme inheritance for LESS themes are not so simple. Glob is only getting main less files and then passes to `dependencyTreeBuilder` function, to get paths to all necessary partials to watch them, that's why your child theme HAVE TO contain main less file without `_` on front (yes, you have to copy them manually from parent).

I'm closing this issue, b/c it's not an issue. 
Also I'm not going to support any things related to LESS anymore, so if you have any questions -> ask community. I work only with SASS and not going to change it (probably LESS suport will be removed in some of future versions, b/c I don't have time to check if everything works fine)

**Comment by keyurshah** [comment]
just to add, alan kent's ebook, Magento 2: Theme Web Page Assets, goes into some detail on using frontool and might help you out with your configuration.

**Comment by amenk** [comment]
Bought that book, did not help ;-)
A note: I was not able to get it running by copying the main .less files either - it then misses the lib files and so on `gulp-notify: [Error running Gulp] Error: 'source/lib/_responsive.less' wasn't found.`

The smartest decision seems to be to finish my current projects using the paint full grunt and LESS way and just use SASS next time ..
