### ISSUE TITLE
Publishing as NPM package

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-frontools#88]
Moved from #46 - @sydekumf

Looks like we have quite big differences in directories structure - helpers are two levels below gulpfile.
Also `config.projectPath` probably needs to be changed to handle installing via composer with rest of magento and as npm package in same time.
Your gulpfile is exporting a module to generate tasks for style compilation - where and how do you handle this stuff? Do you have idea how to handle this for both usage cases?

I'm open to publishing this as a NPM module, but I'm not sure if there is a way to do this, keeping compatibility with default use case via composer (I'm not going to drop this support)

**Comment by Igloczek** [comment]
@sydekumf closing due to lack of feedback

**Comment by joshuaadickerson** [comment]
I just found this project. I noticed that there are no PHP files in this repo. It would make sense to install via npm. The main reason I want to do so is for deployment. I want to use these tools in my build process but I don't want to have to go install this via composer and then install my normal npm packages and then install this. I'd rather just have a single node_modules and have that shared at the root.

**Comment by Igloczek** [comment]
@joshuaadickerson managing paths and overall application architecture make it hard to do it this way.

M2 is designed to be installed through Composer, so your main project repository should have only 3 files `.gitignore`, `composer.json`, `composer.lock`. Any other ways of dealing with it are not recommended and considered as a bad practice.

That's why this project, written purely with JS, is also delivered to M2 as a Composer package.
