### ISSUE TITLE
Generating Magento mixin library 'docs'

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#9]
This is a relatively minor thing, but I thought I would mention it if you wanted to have a go.  If you use the standard Magento 2 build process, there is actually a `css/docs` directory that gets created. This includes an online viewable set of docs for the Magento 2 mixin library.

I think it is basically `cp -r lib/web/css/docs/ pub/static/frontend/Magento/blank/en_US/css/docs/` followed by Less compiling the `source/docs.less` file into `source/docs.css`.

I mention it because if you use the default Magento 2 build process then run this Gulp project on it, the blank theme is deleted and created again but without the docs directory.  I actually think not creating the docs directory by default is a good thing - you don't want it there in production mode.  But it would be convenient if there was say a separate gulp target to cp across the tree and run Less on it - that way people who want to look at the docs can, but it is not there by default. There is not need for `gulp watch` do watch this directory. Its just a once off setup if you want to read those docs.

**Comment by Igloczek** [comment]
This should be separate task. But... this is just copy of pre-generated Magento UI docs, so why we should maintain this, if nobody shouldn't make any changes inside?

**Comment by alankent** [comment]
You can only view it via a web browser. There is one .less file that needs to be compiled into .css, otherwise - yes - it is completely static.

Why is it like this? I don't know the history actually, just that it needs to be done if you want to be able to read the docs. And the path is hard coded into the code so it cannot be put anywhere else from what I can see.

Hmmm, maybe I need to dig more. I do now recall something about it adjusting per site.That is why the .less file needs compiling. It is actually copied into luma etc as well - every theme gets a copy. It must show what the buttons etc look like in *that* theme.

**Comment by Igloczek** [comment]
Ok, I forgot that in LESS is possible to use variables before their definition and Magento UI docs depend on theme variables :boom:

**Comment by Igloczek** [comment]
Resolved in 0.5.0
