### ISSUE TITLE
`dest` in theme.json?

### ISSUE THREAD

**Issue by Hobbit78** [SnowdogApps/magento2-frontools#96]
Hi there,

Awesome tool.
I was wondering, shouldn't the `dest` parameter be located to `pub/static/frontend/vendor/theme` instead of `pub/static/vendor/theme`, like the docs says?

Thanks in advanced!

**Comment by Igloczek** [comment]
But where did you see that?

Docs says:
> `dest` - full path to `pub/static/[theme]`

**Comment by Hobbit78** [comment]
When I look into my `pub` folder, there is no theme defined in `static`.
It is defined in `frontend`.

Or am I wrong?

**Comment by Igloczek** [comment]
`[theme]` mean that you have to put here path to your theme, not `theme` string.
`[area]/[vendor]/[theme]` probably will be more suitable in this place.

**Comment by Hobbit78** [comment]
Yeah, maybe that's better.
After all the `theme.json` does give the right example.

Just want to contribute for make it more clear for other users ;-)
Thanks!

**Comment by Igloczek** [comment]
Great, docs changed. Thanks for contributing!
